import { Injectable } from '@angular/core';

export interface Language {
  code: string;
  name: string;
  flag: string;
  flagImage: string; // Add this new property
}

export interface LearningContent {
  words: { [key: string]: string };
  numbers: { [key: string]: string };
  sentences: { [key: string]: string };
}

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  private languages: Language[] = [
    {
      code: 'en',
      name: 'English',
      flag: '🇬🇧',
      flagImage: '/assets/flags/gb.png',
    },
    {
      code: 'es',
      name: 'Spanish',
      flag: '🇪🇸',
      flagImage: '/assets/flags/es.png',
    },
    {
      code: 'fr',
      name: 'French',
      flag: '🇫🇷',
      flagImage: '/assets/flags/fr.png',
    },
    {
      code: 'de',
      name: 'German',
      flag: '🇩🇪',
      flagImage: '/assets/flags/de.png',
    },
    {
      code: 'it',
      name: 'Italian',
      flag: '🇮🇹',
      flagImage: '/assets/flags/it.png',
    },
    {
      code: 'ja',
      name: 'Japanese',
      flag: '🇯🇵',
      flagImage: '/assets/flags/jp.png',
    },
    {
      code: 'zh',
      name: 'Chinese',
      flag: '🇨🇳',
      flagImage: '/assets/flags/cn.png',
    },
    {
      code: 'ko',
      name: 'Korean',
      flag: '🇰🇷',
      flagImage: '/assets/flags/kr.png',
    },
    {
      code: 'pl',
      name: 'Polish',
      flag: '🇵🇱',
      flagImage: '/assets/flags/pl.png',
    },
    {
      code: 'ru',
      name: 'Russian',
      flag: '🇷🇺',
      flagImage: '/assets/flags/ru.png',
    },
    // { code: 'me', name: 'Montenegrin', flag: '🇲🇪', flagImage: '/assets/flags/me.png' },
    {
      code: 'ar',
      name: 'Arabic',
      flag: '🇸🇦',
      flagImage: '/assets/flags/sa.png',
    },
    {
      code: 'hi',
      name: 'Hindi',
      flag: '🇮🇳',
      flagImage: '/assets/flags/in.png',
    },
    {
      code: 'no',
      name: 'Norwegian',
      flag: '🇳🇴',
      flagImage: '/assets/flags/no.png',
    },
    {
      code: 'da',
      name: 'Danish',
      flag: '🇩🇰',
      flagImage: '/assets/flags/dk.png',
    },
    {
      code: 'sv',
      name: 'Swedish',
      flag: '🇸🇪',
      flagImage: '/assets/flags/se.png',
    },
    {
      code: 'nl',
      name: 'Dutch',
      flag: '🇳🇱',
      flagImage: '/assets/flags/nl.png',
    },
    {
      code: 'tr',
      name: 'Turkish',
      flag: '🇹🇷',
      flagImage: '/assets/flags/tr.png',
    },
    {
      code: 'ro',
      name: 'Romanian',
      flag: '🇷🇴',
      flagImage: '/assets/flags/ro.png',
    },
    {
      code: 'is',
      name: 'Icelandic',
      flag: '🇮🇸',
      flagImage: '/assets/flags/is.png',
    },
    {
      code: 'pt',
      name: 'Portuguese',
      flag: '🇵🇹',
      flagImage: '/assets/flags/pt.png',
    },
    {
      code: 'cy',
      name: 'Welsh',
      flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
      flagImage: '/assets/flags/gb-wls.png',
    },
  ];

  private content: { [key: string]: LearningContent } = {
    en: {
      words: {
        // Essential Nouns
        water: 'water',
        food: 'food',
        restaurant: 'restaurant',
        bathroom: 'bathroom',
        hospital: 'hospital',
        hotel: 'hotel',
        airport: 'airport',
        train: 'train',
        bus: 'bus',
        taxi: 'taxi',
        // Common Adjectives
        good: 'good',
        bad: 'bad',
        big: 'big',
        small: 'small',
        hot: 'hot',
        cold: 'cold',
        // Essential Verbs
        'to eat': 'to eat',
        'to drink': 'to drink',
        'to sleep': 'to sleep',
        'to go': 'to go',
        'to help': 'to help',
        thanks: 'thanks',
      },
      numbers: {
        '0': 'zero',
        '1': 'one',
        '2': 'two',
        '3': 'three',
        '4': 'four',
        '5': 'five',
        '6': 'six',
        '7': 'seven',
        '8': 'eight',
        '9': 'nine',
        '10': 'ten',
        '20': 'twenty',
        '30': 'thirty',
        '40': 'forty',
        '50': 'fifty',
        '100': 'hundred',
        '1000': 'thousand',
      },
      sentences: {
        // Greetings
        Hello: 'Hello',
        'Good morning': 'Good morning',
        'Good afternoon': 'Good afternoon',
        'Good night': 'Good night',
        Goodbye: 'Goodbye',
        // Essential Phrases
        'How are you?': 'How are you?',
        'I am fine': 'I am fine',
        'Thank you': 'Thank you',
        "You're welcome": "You're welcome",
        Please: 'Please',
        'Excuse me': 'Excuse me',
        "I'm sorry": "I'm sorry",
        // Emergency Phrases
        'I need help': 'I need help',
        'I am lost': 'I am lost',
        "I don't understand": "I don't understand",
        'Do you speak English?': 'Do you speak English?',
        'Where is the bathroom?': 'Where is the bathroom?',
        // Practical Phrases
        'How much does it cost?': 'How much does it cost?',
        'Can you help me?': 'Can you help me?',
        'I would like...': 'I would like...',
        'The check, please': 'The check, please',
      },
    },
    es: {
      words: {
        // Essential Nouns
        water: 'agua',
        food: 'comida',
        restaurant: 'restaurante',
        bathroom: 'baño',
        hospital: 'hospital',
        hotel: 'hotel',
        airport: 'aeropuerto',
        train: 'tren',
        bus: 'autobús',
        taxi: 'taxi',
        // Common Adjectives
        good: 'bueno',
        bad: 'malo',
        big: 'grande',
        small: 'pequeño',
        hot: 'caliente',
        cold: 'frío',
        // Essential Verbs
        'to eat': 'comer',
        'to drink': 'beber',
        'to sleep': 'dormir',
        'to go': 'ir',
        'to help': 'ayudar',
        thanks: 'gracias',
      },
      numbers: {
        '0': 'cero',
        '1': 'uno',
        '2': 'dos',
        '3': 'tres',
        '4': 'cuatro',
        '5': 'cinco',
        '6': 'seis',
        '7': 'siete',
        '8': 'ocho',
        '9': 'nueve',
        '10': 'diez',
        '20': 'veinte',
        '30': 'treinta',
        '40': 'cuarenta',
        '50': 'cincuenta',
        '100': 'cien',
        '1000': 'mil',
      },
      sentences: {
        // Greetings
        Hello: '¡Hola!',
        'Good morning': '¡Buenos días!',
        'Good afternoon': '¡Buenas tardes!',
        'Good night': '¡Buenas noches!',
        Goodbye: '¡Adiós!',
        // Essential Phrases
        'How are you?': '¿Cómo estás?',
        'I am fine': 'Estoy bien',
        'Thank you': 'Gracias',
        "You're welcome": 'De nada',
        Please: 'Por favor',
        'Excuse me': 'Perdón',
        "I'm sorry": 'Lo siento',
        // Emergency Phrases
        'I need help': 'Necesito ayuda',
        'I am lost': 'Estoy perdido',
        "I don't understand": 'No entiendo',
        'Do you speak English?': '¿Habla inglés?',
        'Where is the bathroom?': '¿Dónde está el baño?',
        // Practical Phrases
        'How much does it cost?': '¿Cuánto cuesta?',
        'Can you help me?': '¿Puede ayudarme?',
        'I would like...': 'Quisiera...',
        'The check, please': 'La cuenta, por favor',
      },
    },
    fr: {
      words: {
        // Essential Nouns
        water: 'eau',
        food: 'nourriture',
        restaurant: 'restaurant',
        bathroom: 'toilettes',
        hospital: 'hôpital',
        hotel: 'hôtel',
        airport: 'aéroport',
        train: 'train',
        bus: 'bus',
        taxi: 'taxi',
        // Common Adjectives
        good: 'bon',
        bad: 'mauvais',
        big: 'grand',
        small: 'petit',
        hot: 'chaud',
        cold: 'froid',
        // Essential Verbs
        'to eat': 'manger',
        'to drink': 'boire',
        'to sleep': 'dormir',
        'to go': 'aller',
        'to help': 'aider',
        thanks: 'merci',
      },
      numbers: {
        '0': 'zéro',
        '1': 'un',
        '2': 'deux',
        '3': 'trois',
        '4': 'quatre',
        '5': 'cinq',
        '6': 'six',
        '7': 'sept',
        '8': 'huit',
        '9': 'neuf',
        '10': 'dix',
        '20': 'vingt',
        '30': 'trente',
        '40': 'quarante',
        '50': 'cinquante',
        '100': 'cent',
        '1000': 'mille',
      },
      sentences: {
        // Greetings
        Hello: 'Bonjour',
        'Good morning': 'Bonjour',
        'Good afternoon': 'Bon après-midi',
        'Good night': 'Bonne nuit',
        Goodbye: 'Au revoir',
        // Essential Phrases
        'How are you?': 'Comment allez-vous?',
        'I am fine': 'Je vais bien',
        'Thank you': 'Merci',
        "You're welcome": 'De rien',
        Please: "S'il vous plaît",
        'Excuse me': 'Excusez-moi',
        "I'm sorry": 'Je suis désolé',
        // Emergency Phrases
        'I need help': "J'ai besoin d'aide",
        'I am lost': 'Je suis perdu',
        "I don't understand": 'Je ne comprends pas',
        'Do you speak English?': 'Parlez-vous anglais?',
        'Where is the bathroom?': 'Où sont les toilettes?',
        // Practical Phrases
        'How much does it cost?': 'Combien ça coûte?',
        'Can you help me?': "Pouvez-vous m'aider?",
        'I would like...': 'Je voudrais...',
        'The check, please': "L'addition, s'il vous plaît",
      },
    },
    de: {
      words: {
        // Essential Nouns
        water: 'Wasser',
        food: 'Essen',
        restaurant: 'Restaurant',
        bathroom: 'Toilette',
        hospital: 'Krankenhaus',
        hotel: 'Hotel',
        airport: 'Flughafen',
        train: 'Zug',
        bus: 'Bus',
        taxi: 'Taxi',
        // Common Adjectives
        good: 'gut',
        bad: 'schlecht',
        big: 'groß',
        small: 'klein',
        hot: 'heiß',
        cold: 'kalt',
        // Essential Verbs
        'to eat': 'essen',
        'to drink': 'trinken',
        'to sleep': 'schlafen',
        'to go': 'gehen',
        'to help': 'helfen',
        thanks: 'danke',
      },
      numbers: {
        '0': 'null',
        '1': 'eins',
        '2': 'zwei',
        '3': 'drei',
        '4': 'vier',
        '5': 'fünf',
        '6': 'sechs',
        '7': 'sieben',
        '8': 'acht',
        '9': 'neun',
        '10': 'zehn',
        '20': 'zwanzig',
        '30': 'dreißig',
        '40': 'vierzig',
        '50': 'fünfzig',
        '100': 'hundert',
        '1000': 'tausend',
      },
      sentences: {
        // Greetings
        Hello: 'Hallo',
        'Good morning': 'Guten Morgen',
        'Good afternoon': 'Guten Tag',
        'Good night': 'Gute Nacht',
        Goodbye: 'Auf Wiedersehen',
        // Essential Phrases
        'How are you?': 'Wie geht es Ihnen?',
        'I am fine': 'Mir geht es gut',
        'Thank you': 'Danke',
        "You're welcome": 'Bitte',
        Please: 'Bitte',
        'Excuse me': 'Entschuldigung',
        "I'm sorry": 'Es tut mir leid',
        // Emergency Phrases
        'I need help': 'Ich brauche Hilfe',
        'I am lost': 'Ich habe mich verirrt',
        "I don't understand": 'Ich verstehe nicht',
        'Do you speak English?': 'Sprechen Sie Englisch?',
        'Where is the bathroom?': 'Wo ist die Toilette?',
        // Practical Phrases
        'How much does it cost?': 'Wie viel kostet das?',
        'Can you help me?': 'Können Sie mir helfen?',
        'I would like...': 'Ich möchte...',
        'The check, please': 'Die Rechnung, bitte',
      },
    },

    it: {
      words: {
        // Essential Nouns
        water: 'acqua',
        food: 'cibo',
        restaurant: 'ristorante',
        bathroom: 'bagno',
        hospital: 'ospedale',
        hotel: 'albergo',
        airport: 'aeroporto',
        train: 'treno',
        bus: 'autobus',
        taxi: 'taxi',
        // Common Adjectives
        good: 'buono',
        bad: 'cattivo',
        big: 'grande',
        small: 'piccolo',
        hot: 'caldo',
        cold: 'freddo',
        // Essential Verbs
        'to eat': 'mangiare',
        'to drink': 'bere',
        'to sleep': 'dormire',
        'to go': 'andare',
        'to help': 'aiutare',
        thanks: 'grazie',
      },
      numbers: {
        '0': 'zero',
        '1': 'uno',
        '2': 'due',
        '3': 'tre',
        '4': 'quattro',
        '5': 'cinque',
        '6': 'sei',
        '7': 'sette',
        '8': 'otto',
        '9': 'nove',
        '10': 'dieci',
        '20': 'venti',
        '30': 'trenta',
        '40': 'quaranta',
        '50': 'cinquanta',
        '100': 'cento',
        '1000': 'mille',
      },
      sentences: {
        // Greetings
        Hello: 'Ciao',
        'Good morning': 'Buongiorno',
        'Good afternoon': 'Buon pomeriggio',
        'Good night': 'Buonanotte',
        Goodbye: 'Arrivederci',
        // Essential Phrases
        'How are you?': 'Come stai?',
        'I am fine': 'Sto bene',
        'Thank you': 'Grazie',
        "You're welcome": 'Prego',
        Please: 'Per favore',
        'Excuse me': 'Scusi',
        "I'm sorry": 'Mi dispiace',
        // Emergency Phrases
        'I need help': 'Ho bisogno di aiuto',
        'I am lost': 'Mi sono perso',
        "I don't understand": 'Non capisco',
        'Do you speak English?': 'Parla inglese?',
        'Where is the bathroom?': "Dov'è il bagno?",
        // Practical Phrases
        'How much does it cost?': 'Quanto costa?',
        'Can you help me?': 'Può aiutarmi?',
        'I would like...': 'Vorrei...',
        'The check, please': 'Il conto, per favore',
      },
    },

    ja: {
      words: {
        // Essential Nouns
        water: '水 (mizu)',
        food: '食べ物 (tabemono)',
        restaurant: 'レストラン (resutoran)',
        bathroom: 'トイレ (toire)',
        hospital: '病院 (byōin)',
        hotel: 'ホテル (hoteru)',
        airport: '空港 (kūkō)',
        train: '電車 (densha)',
        bus: 'バス (basu)',
        taxi: 'タクシー (takushī)',
        // Common Adjectives
        good: '良い (yoi)',
        bad: '悪い (warui)',
        big: '大きい (ōkii)',
        small: '小さい (chiisai)',
        hot: '熱い (atsui)',
        cold: '寒い (samui)',
        // Essential Verbs
        'to eat': '食べる (taberu)',
        'to drink': '飲む (nomu)',
        'to sleep': '寝る (neru)',
        'to go': '行く (iku)',
        'to help': '助ける (tasukeru)',
        thanks: 'ありがとう (arigatō)',
      },
      numbers: {
        '0': '零 (rei)',
        '1': '一 (ichi)',
        '2': '二 (ni)',
        '3': '三 (san)',
        '4': '四 (yon/shi)',
        '5': '五 (go)',
        '6': '六 (roku)',
        '7': '七 (nana/shichi)',
        '8': '八 (hachi)',
        '9': '九 (kyū/ku)',
        '10': '十 (jū)',
        '20': '二十 (nijū)',
        '30': '三十 (sanjū)',
        '40': '四十 (yonjū)',
        '50': '五十 (gojū)',
        '100': '百 (hyaku)',
        '1000': '千 (sen)',
      },
      sentences: {
        // Greetings
        Hello: 'こんにちは (Konnichiwa)',
        'Good morning': 'おはようございます (Ohayō gozaimasu)',
        'Good afternoon': 'こんにちは (Konnichiwa)',
        'Good night': 'おやすみなさい (Oyasuminasai)',
        Goodbye: 'さようなら (Sayōnara)',
        // Essential Phrases
        'How are you?': 'お元気ですか？ (O-genki desu ka?)',
        'I am fine': '元気です (Genki desu)',
        'Thank you': 'ありがとうございます (Arigatō gozaimasu)',
        "You're welcome": 'どういたしまして (Dō itashimashite)',
        Please: 'お願いします (Onegaishimasu)',
        'Excuse me': 'すみません (Sumimasen)',
        "I'm sorry": 'ごめんなさい (Gomen nasai)',
        // Emergency Phrases
        'I need help': '助けてください (Tasukete kudasai)',
        'I am lost': '道に迷いました (Michi ni mayoimashita)',
        "I don't understand": '分かりません (Wakarimasen)',
        'Do you speak English?': '英語を話しますか？ (Eigo o hanashimasu ka?)',
        'Where is the bathroom?':
          'トイレはどこですか？ (Toire wa doko desu ka?)',
        // Practical Phrases
        'How much does it cost?': 'いくらですか？ (Ikura desu ka?)',
        'Can you help me?':
          '手伝っていただけますか？ (Tetsudatte itadakemasu ka?)',
        'I would like...': '...をお願いします (...o onegaishimasu)',
        'The check, please': 'お会計をお願いします (O-kaikei o onegaishimasu)',
      },
    },

    zh: {
      words: {
        // Essential Nouns
        water: '水 (shuǐ)',
        food: '食物 (shíwù)',
        restaurant: '餐厅 (cāntīng)',
        bathroom: '洗手间 (xǐshǒujiān)',
        hospital: '医院 (yīyuàn)',
        hotel: '酒店 (jiǔdiàn)',
        airport: '机场 (jīchǎng)',
        train: '火车 (huǒchē)',
        bus: '公共汽车 (gōnggòng qìchē)',
        taxi: '出租车 (chūzūchē)',
        // Common Adjectives
        good: '好 (hǎo)',
        bad: '坏 (huài)',
        big: '大 (dà)',
        small: '小 (xiǎo)',
        hot: '热 (rè)',
        cold: '冷 (lěng)',
        // Essential Verbs
        'to eat': '吃 (chī)',
        'to drink': '喝 (hē)',
        'to sleep': '睡觉 (shuìjiào)',
        'to go': '去 (qù)',
        'to help': '帮助 (bāngzhù)',
        thanks: '谢谢 (xièxie)',
      },
      numbers: {
        '0': '零 (líng)',
        '1': '一 (yī)',
        '2': '二 (èr)',
        '3': '三 (sān)',
        '4': '四 (sì)',
        '5': '五 (wǔ)',
        '6': '六 (liù)',
        '7': '七 (qī)',
        '8': '八 (bā)',
        '9': '九 (jiǔ)',
        '10': '十 (shí)',
        '20': '二十 (èrshí)',
        '30': '三十 (sānshí)',
        '40': '四十 (sìshí)',
        '50': '五十 (wǔshí)',
        '100': '百 (bǎi)',
        '1000': '千 (qiān)',
      },
      sentences: {
        // Greetings
        Hello: '你好 (Nǐ hǎo)',
        'Good morning': '早上好 (Zǎoshang hǎo)',
        'Good afternoon': '下午好 (Xiàwǔ hǎo)',
        'Good night': "晚安 (Wǎn'ān)",
        Goodbye: '再见 (Zàijiàn)',
        // Essential Phrases
        'How are you?': '你好吗？(Nǐ hǎo ma?)',
        'I am fine': '我很好 (Wǒ hěn hǎo)',
        'Thank you': '谢谢 (Xièxie)',
        "You're welcome": '不客气 (Bú kèqi)',
        Please: '请 (Qǐng)',
        'Excuse me': '对不起 (Duìbùqǐ)',
        "I'm sorry": '抱歉 (Bàoqiàn)',
        // Emergency Phrases
        'I need help': '我需要帮助 (Wǒ xūyào bāngzhù)',
        'I am lost': '我迷路了 (Wǒ mílù le)',
        "I don't understand": '我不明白 (Wǒ bù míngbai)',
        'Do you speak English?': '你会说英语吗？(Nǐ huì shuō yīngyǔ ma?)',
        'Where is the bathroom?': '洗手间在哪里？(Xǐshǒujiān zài nǎli?)',
        // Practical Phrases
        'How much does it cost?': '多少钱？(Duōshao qián?)',
        'Can you help me?': '你能帮我吗？(Nǐ néng bāng wǒ ma?)',
        'I would like...': '我想要... (Wǒ xiǎng yào...)',
        'The check, please': '请结账 (Qǐng jiézhàng)',
      },
    },

    ko: {
      words: {
        // Essential Nouns
        water: '물 (mul)',
        food: '음식 (eumsik)',
        restaurant: '식당 (sikdang)',
        bathroom: '화장실 (hwajangsil)',
        hospital: '병원 (byeongwon)',
        hotel: '호텔 (hotel)',
        airport: '공항 (gonghang)',
        train: '기차 (gicha)',
        bus: '버스 (beoseu)',
        taxi: '택시 (taeksi)',
        // Common Adjectives
        good: '좋은 (jo-eun)',
        bad: '나쁜 (nappeun)',
        big: '큰 (keun)',
        small: '작은 (jag-eun)',
        hot: '뜨거운 (tteugeoun)',
        cold: '추운 (chu-un)',
        // Essential Verbs
        'to eat': '먹다 (meokda)',
        'to drink': '마시다 (masida)',
        'to sleep': '자다 (jada)',
        'to go': '가다 (gada)',
        'to help': '돕다 (dopda)',
        thanks: '감사합니다 (gamsahamnida)',
      },
      numbers: {
        '0': '영 (yeong)',
        '1': '일 (il)',
        '2': '이 (i)',
        '3': '삼 (sam)',
        '4': '사 (sa)',
        '5': '오 (o)',
        '6': '육 (yuk)',
        '7': '칠 (chil)',
        '8': '팔 (pal)',
        '9': '구 (gu)',
        '10': '십 (sip)',
        '20': '이십 (isip)',
        '30': '삼십 (samsip)',
        '40': '사십 (sasip)',
        '50': '오십 (osip)',
        '100': '백 (baek)',
        '1000': '천 (cheon)',
      },
      sentences: {
        // Greetings
        Hello: '안녕하세요 (Annyeonghaseyo)',
        'Good morning': '안녕하세요 (Annyeonghaseyo)',
        'Good afternoon': '안녕하세요 (Annyeonghaseyo)',
        'Good night': '안녕히 주무세요 (Annyeonghi jumuseyo)',
        Goodbye: '안녕히 가세요 (Annyeonghi gaseyo)',
        // Essential Phrases
        'How are you?': '어떻게 지내세요? (Eotteoke jinaeseyo?)',
        'I am fine': '잘 지내요 (Jal jinaeyo)',
        'Thank you': '감사합니다 (Gamsahamnida)',
        "You're welcome": '천만에요 (Cheonmaneyo)',
        Please: '주세요 (Juseyo)',
        'Excuse me': '실례합니다 (Sillyehamnida)',
        "I'm sorry": '죄송합니다 (Joesonghamnida)',
        // Emergency Phrases
        'I need help': '도움이 필요해요 (Doum-i pilyohaeyo)',
        'I am lost': '길을 잃었어요 (Gil-eul ilheosseoyo)',
        "I don't understand": '이해가 안 돼요 (Ihaega an dwaeyo)',
        'Do you speak English?':
          '영어 하실 줄 아세요? (Yeong-eo hasil jul aseyo?)',
        'Where is the bathroom?': '화장실이 어디예요? (Hwajangsil-i eodiyeyo?)',
        // Practical Phrases
        'How much does it cost?': '얼마예요? (Eolmayeyo?)',
        'Can you help me?': '도와주실 수 있나요? (Dowajusil su innayo?)',
        'I would like...': '...주세요 (...juseyo)',
        'The check, please': '계산서 주세요 (Gyesanseo juseyo)',
      },
    },

    ru: {
      words: {
        // Essential Nouns
        water: 'вода (voda)',
        food: 'еда (yeda)',
        restaurant: 'ресторан (restoran)',
        bathroom: 'туалет (tualet)',
        hospital: 'больница (bolnitsa)',
        hotel: 'отель (otel)',
        airport: 'аэропорт (aeroport)',
        train: 'поезд (poyezd)',
        bus: 'автобус (avtobus)',
        taxi: 'такси (taksi)',
        // Common Adjectives
        good: 'хороший (khoroshiy)',
        bad: 'плохой (plokhoy)',
        big: 'большой (bolshoy)',
        small: 'маленький (malenkiy)',
        hot: 'горячий (goryachiy)',
        cold: 'холодный (kholodnyy)',
        // Essential Verbs
        'to eat': 'есть (yest)',
        'to drink': 'пить (pit)',
        'to sleep': 'спать (spat)',
        'to go': 'идти (idti)',
        'to help': 'помогать (pomogat)',
        thanks: 'спасибо (spasibo)',
      },
      numbers: {
        '0': 'ноль (nol)',
        '1': 'один (odin)',
        '2': 'два (dva)',
        '3': 'три (tri)',
        '4': 'четыре (chetyre)',
        '5': 'пять (pyat)',
        '6': 'шесть (shest)',
        '7': 'семь (sem)',
        '8': 'восемь (vosem)',
        '9': 'девять (devyat)',
        '10': 'десять (desyat)',
        '20': 'двадцать (dvadtsat)',
        '30': 'тридцать (tridtsat)',
        '40': 'сорок (sorok)',
        '50': 'пятьдесят (pyatdesyat)',
        '100': 'сто (sto)',
        '1000': 'тысяча (tysyacha)',
      },
      sentences: {
        // Greetings
        Hello: 'Здравствуйте (Zdravstvuyte)',
        'Good morning': 'Доброе утро (Dobroye utro)',
        'Good afternoon': 'Добрый день (Dobryy den)',
        'Good night': 'Спокойной ночи (Spokoynoy nochi)',
        Goodbye: 'До свидания (Do svidaniya)',
        // Essential Phrases
        'How are you?': 'Как дела? (Kak dela?)',
        'I am fine': 'У меня всё хорошо (U menya vsyo khorosho)',
        'Thank you': 'Спасибо (Spasibo)',
        "You're welcome": 'Пожалуйста (Pozhaluysta)',
        Please: 'Пожалуйста (Pozhaluysta)',
        'Excuse me': 'Извините (Izvinite)',
        "I'm sorry": 'Простите (Prostite)',
        // Emergency Phrases
        'I need help': 'Мне нужна помощь (Mne nuzhna pomoshch)',
        'I am lost': 'Я заблудился (Ya zabludilsya)',
        "I don't understand": 'Я не понимаю (Ya ne ponimayu)',
        'Do you speak English?':
          'Вы говорите по-английски? (Vy govorite po-angliyski?)',
        'Where is the bathroom?': 'Где туалет? (Gde tualet?)',
        // Practical Phrases
        'How much does it cost?': 'Сколько это стоит? (Skolko eto stoit?)',
        'Can you help me?': 'Вы можете мне помочь? (Vy mozhete mne pomoch?)',
        'I would like...': 'Я бы хотел... (Ya by khotel...)',
        'The check, please': 'Счёт, пожалуйста (Schyot, pozhaluysta)',
      },
    },

    me: {
      words: {
        // Essential Nouns
        water: 'voda',
        food: 'hrana',
        restaurant: 'restoran',
        bathroom: 'kupatilo',
        hospital: 'bolnica',
        hotel: 'hotel',
        airport: 'aerodrom',
        train: 'voz',
        bus: 'autobus',
        taxi: 'taksi',
        // Common Adjectives
        good: 'dobar',
        bad: 'loš',
        big: 'veliki',
        small: 'mali',
        hot: 'vruć',
        cold: 'hladan',
        // Essential Verbs
        'to eat': 'jesti',
        'to drink': 'piti',
        'to sleep': 'spavati',
        'to go': 'ići',
        'to help': 'pomoći',
        thanks: 'hvala',
      },
      numbers: {
        '0': 'nula',
        '1': 'jedan',
        '2': 'dva',
        '3': 'tri',
        '4': 'četiri',
        '5': 'pet',
        '6': 'šest',
        '7': 'sedam',
        '8': 'osam',
        '9': 'devet',
        '10': 'deset',
        '20': 'dvadeset',
        '30': 'trideset',
        '40': 'četrdeset',
        '50': 'pedeset',
        '100': 'sto',
        '1000': 'hiljada',
      },
      sentences: {
        // Greetings
        Hello: 'Zdravo',
        'Good morning': 'Dobro jutro',
        'Good afternoon': 'Dobar dan',
        'Good night': 'Laku noć',
        Goodbye: 'Doviđenja',
        // Essential Phrases
        'How are you?': 'Kako si?',
        'I am fine': 'Dobro sam',
        'Thank you': 'Hvala',
        "You're welcome": 'Nema na čemu',
        Please: 'Molim',
        'Excuse me': 'Izvinite',
        "I'm sorry": 'Žao mi je',
        // Emergency Phrases
        'I need help': 'Treba mi pomoć',
        'I am lost': 'Izgubio sam se',
        "I don't understand": 'Ne razumijem',
        'Do you speak English?': 'Govoriš li engleski?',
        'Where is the bathroom?': 'Gdje je kupatilo?',
        // Practical Phrases
        'How much does it cost?': 'Koliko košta?',
        'Can you help me?': 'Možete li mi pomoći?',
        'I would like...': 'Želio bih...',
        'The check, please': 'Račun, molim vas',
      },
    },

    pl: {
      words: {
        // Essential Nouns
        water: 'woda',
        food: 'jedzenie',
        restaurant: 'restauracja',
        bathroom: 'łazienka',
        hospital: 'szpital',
        hotel: 'hotel',
        airport: 'lotnisko',
        train: 'pociąg',
        bus: 'autobus',
        taxi: 'taksówka',
        // Common Adjectives
        good: 'dobry',
        bad: 'zły',
        big: 'duży',
        small: 'mały',
        hot: 'gorący',
        cold: 'zimny',
        // Essential Verbs
        'to eat': 'jeść',
        'to drink': 'pić',
        'to sleep': 'spać',
        'to go': 'iść',
        'to help': 'pomóc',
        thanks: 'dziękuję',
      },
      numbers: {
        '0': 'zero',
        '1': 'jeden',
        '2': 'dwa',
        '3': 'trzy',
        '4': 'cztery',
        '5': 'pięć',
        '6': 'sześć',
        '7': 'siedem',
        '8': 'osiem',
        '9': 'dziewięć',
        '10': 'dziesięć',
        '20': 'dwadzieścia',
        '30': 'trzydzieści',
        '40': 'czterdzieści',
        '50': 'pięćdziesiąt',
        '100': 'sto',
        '1000': 'tysiąc',
      },
      sentences: {
        // Greetings
        Hello: 'Cześć',
        'Good morning': 'Dzień dobry',
        'Good afternoon': 'Dzień dobry',
        'Good night': 'Dobranoc',
        Goodbye: 'Do widzenia',
        // Essential Phrases
        'How are you?': 'Jak się masz?',
        'I am fine': 'Mam się dobrze',
        'Thank you': 'Dziękuję',
        "You're welcome": 'Proszę bardzo',
        Please: 'Proszę',
        'Excuse me': 'Przepraszam',
        "I'm sorry": 'Przykro mi',
        // Emergency Phrases
        'I need help': 'Potrzebuję pomocy',
        'I am lost': 'Zgubiłem się',
        "I don't understand": 'Nie rozumiem',
        'Do you speak English?': 'Czy mówisz po angielsku?',
        'Where is the bathroom?': 'Gdzie jest łazienka?',
        // Practical Phrases
        'How much does it cost?': 'Ile to kosztuje?',
        'Can you help me?': 'Czy możesz mi pomóc?',
        'I would like...': 'Chciałbym...',
        'The check, please': 'Rachunek poproszę',
      },
    },
    ar: {
      words: {
        // Essential Nouns
        water: "ماء (maa')",
        food: "طعام (ta'am)",
        restaurant: "مطعم (mat'am)",
        bathroom: 'حمام (hammam)',
        hospital: 'مستشفى (mustashfa)',
        hotel: 'فندق (funduq)',
        airport: 'مطار (matar)',
        train: 'قطار (qitar)',
        bus: 'حافلة (hafila)',
        taxi: 'تاكسي (taksi)',
        // Common Adjectives
        good: 'جيد (jayyid)',
        bad: "سيء (sayyi')",
        big: 'كبير (kabir)',
        small: 'صغير (saghir)',
        hot: 'حار (har)',
        cold: 'بارد (barid)',
        // Essential Verbs
        'to eat': "يأكل (ya'kul)",
        'to drink': 'يشرب (yashrab)',
        'to sleep': 'ينام (yanam)',
        'to go': 'يذهب (yathhab)',
        'to help': "يساعد (yusa'id)",
        thanks: 'شكراً (shukran)',
      },
      numbers: {
        '0': 'صفر (sifr)',
        '1': 'واحد (wahid)',
        '2': 'اثنان (ithnan)',
        '3': 'ثلاثة (thalatha)',
        '4': "أربعة (arba'a)",
        '5': 'خمسة (khamsa)',
        '6': 'ستة (sitta)',
        '7': "سبعة (sab'a)",
        '8': 'ثمانية (thamaniya)',
        '9': "تسعة (tis'a)",
        '10': 'عشرة (ashara)',
        '20': 'عشرون (ishrun)',
        '30': 'ثلاثون (thalathun)',
        '40': "أربعون (arba'un)",
        '50': 'خمسون (khamsun)',
        '100': "مئة (mi'a)",
        '1000': 'ألف (alf)',
      },
      sentences: {
        // Greetings
        Hello: 'مرحباً (marhaban)',
        'Good morning': 'صباح الخير (sabah al-khayr)',
        'Good afternoon': "مساء الخير (masa' al-khayr)",
        'Good night': 'تصبح على خير (tusbih ala khayr)',
        Goodbye: "مع السلامة (ma'a as-salama)",
        // Essential Phrases
        'How are you?': 'كيف حالك؟ (kayf halak?)',
        'I am fine': 'أنا بخير (ana bikhayr)',
        'Thank you': 'شكراً (shukran)',
        "You're welcome": 'عفواً (afwan)',
        Please: 'من فضلك (min fadlak)',
        'Excuse me': "عذراً ('uthran)",
        "I'm sorry": 'آسف (asif)',
        // Emergency Phrases
        'I need help': "أحتاج مساعدة (ahtaju musa'ada)",
        'I am lost': "أنا ضائع (ana da'i')",
        "I don't understand": 'لا أفهم (la afham)',
        'Do you speak English?':
          'هل تتكلم الإنجليزية؟ (hal tatakallam al-injliziyya?)',
        'Where is the bathroom?': 'أين الحمام؟ (ayna al-hammam?)',
        // Practical Phrases
        'How much does it cost?': 'كم التكلفة؟ (kam at-taklufa?)',
        'Can you help me?': "هل يمكنك مساعدتي؟ (hal yumkinuka musa'adati?)",
        'I would like...': 'أريد... (urid...)',
        'The check, please': 'الحساب من فضلك (al-hisab min fadlak)',
      },
    },
    hi: {
      words: {
        // Essential Nouns
        water: 'पानी (paani)',
        food: 'खाना (khaana)',
        restaurant: 'रेस्तरां (restoraan)',
        bathroom: 'शौचालय (shauchalay)',
        hospital: 'अस्पताल (aspatal)',
        hotel: 'होटल (hotel)',
        airport: 'हवाई अड्डा (havai adda)',
        train: 'रेलगाड़ी (relgaadi)',
        bus: 'बस (bas)',
        taxi: 'टैक्सी (taxi)',
        // Common Adjectives
        good: 'अच्छा (accha)',
        bad: 'बुरा (bura)',
        big: 'बड़ा (bada)',
        small: 'छोटा (chota)',
        hot: 'गरम (garam)',
        cold: 'ठंडा (thanda)',
        // Essential Verbs
        'to eat': 'खाना (khaana)',
        'to drink': 'पीना (peena)',
        'to sleep': 'सोना (sona)',
        'to go': 'जाना (jaana)',
        'to help': 'मदद करना (madad karna)',
        thanks: 'धन्यवाद (dhanyavaad)',
      },
      numbers: {
        '0': 'शून्य (shunya)',
        '1': 'एक (ek)',
        '2': 'दो (do)',
        '3': 'तीन (teen)',
        '4': 'चार (chaar)',
        '5': 'पाँच (paanch)',
        '6': 'छह (chah)',
        '7': 'सात (saat)',
        '8': 'आठ (aath)',
        '9': 'नौ (nau)',
        '10': 'दस (das)',
        '20': 'बीस (bees)',
        '30': 'तीस (tees)',
        '40': 'चालीस (chalees)',
        '50': 'पचास (pachaas)',
        '100': 'सौ (sau)',
        '1000': 'हज़ार (hazaar)',
      },
      sentences: {
        // Greetings
        Hello: 'नमस्ते (namaste)',
        'Good morning': 'सुप्रभात (suprabhat)',
        'Good afternoon': 'नमस्कार (namaskar)',
        'Good night': 'शुभ रात्रि (shubh ratri)',
        Goodbye: 'अलविदा (alvida)',
        // Essential Phrases
        'How are you?': 'आप कैसे हैं? (aap kaise hain?)',
        'I am fine': 'मैं ठीक हूं (main theek hoon)',
        'Thank you': 'धन्यवाद (dhanyavaad)',
        "You're welcome": 'स्वागत है (swaagat hai)',
        Please: 'कृपया (kripya)',
        'Excuse me': 'क्षमा कीजिए (kshama keejiye)',
        "I'm sorry": 'मुझे खेद है (mujhe khed hai)',
        // Emergency Phrases
        'I need help': 'मुझे मदद चाहिए (mujhe madad chahiye)',
        'I am lost': 'मैं खो गया हूं (main kho gaya hoon)',
        "I don't understand": 'मैं नहीं समझता (main nahi samajhta)',
        'Do you speak English?':
          'क्या आप अंग्रेज़ी बोलते हैं? (kya aap angrezi bolte hain?)',
        'Where is the bathroom?': 'बाथरूम कहाँ है? (bathroom kahan hai?)',
        // Practical Phrases
        'How much does it cost?': 'यह कितने का है? (yeh kitne ka hai?)',
        'Can you help me?':
          'क्या आप मेरी मदद कर सकते हैं? (kya aap meri madad kar sakte hain?)',
        'I would like...': 'मैं चाहूंगा... (main chahunga...)',
        'The check, please': 'बिल लाइए (bill laiye)',
      },
    },
    no: {
      words: {
        // Essential Nouns
        water: 'vann',
        food: 'mat',
        restaurant: 'restaurant',
        bathroom: 'toalett',
        hospital: 'sykehus',
        hotel: 'hotell',
        airport: 'flyplass',
        train: 'tog',
        bus: 'buss',
        taxi: 'taxi',
        // Common Adjectives
        good: 'bra',
        bad: 'dårlig',
        big: 'stor',
        small: 'liten',
        hot: 'varm',
        cold: 'kald',
        // Essential Verbs
        'to eat': 'spise',
        'to drink': 'drikke',
        'to sleep': 'sove',
        'to go': 'gå',
        'to help': 'hjelpe',
        thanks: 'takk',
      },
      numbers: {
        '0': 'null',
        '1': 'en',
        '2': 'to',
        '3': 'tre',
        '4': 'fire',
        '5': 'fem',
        '6': 'seks',
        '7': 'sju',
        '8': 'åtte',
        '9': 'ni',
        '10': 'ti',
        '20': 'tjue',
        '30': 'tretti',
        '40': 'førti',
        '50': 'femti',
        '100': 'hundre',
        '1000': 'tusen',
      },
      sentences: {
        // Greetings
        Hello: 'Hallo',
        'Good morning': 'God morgen',
        'Good afternoon': 'God ettermiddag',
        'Good night': 'God natt',
        Goodbye: 'Ha det',
        // Essential Phrases
        'How are you?': 'Hvordan har du det?',
        'I am fine': 'Jeg har det bra',
        'Thank you': 'Takk',
        "You're welcome": 'Vær så god',
        Please: 'Vær så snill',
        'Excuse me': 'Unnskyld',
        "I'm sorry": 'Jeg beklager',
        // Emergency Phrases
        'I need help': 'Jeg trenger hjelp',
        'I am lost': 'Jeg har gått meg vill',
        "I don't understand": 'Jeg forstår ikke',
        'Do you speak English?': 'Snakker du engelsk?',
        'Where is the bathroom?': 'Hvor er toalettet?',
        // Practical Phrases
        'How much does it cost?': 'Hvor mye koster det?',
        'Can you help me?': 'Kan du hjelpe meg?',
        'I would like...': 'Jeg vil gjerne ha...',
        'The check, please': 'Regningen, takk',
      },
    },
    da: {
      words: {
        // Essential Nouns
        water: 'vand',
        food: 'mad',
        restaurant: 'restaurant',
        bathroom: 'badeværelse',
        hospital: 'hospital',
        hotel: 'hotel',
        airport: 'lufthavn',
        train: 'tog',
        bus: 'bus',
        taxi: 'taxa',
        // Common Adjectives
        good: 'god',
        bad: 'dårlig',
        big: 'stor',
        small: 'lille',
        hot: 'varm',
        cold: 'kold',
        // Essential Verbs
        'to eat': 'spise',
        'to drink': 'drikke',
        'to sleep': 'sove',
        'to go': 'gå',
        'to help': 'hjælpe',
        thanks: 'tak',
      },
      numbers: {
        '0': 'nul',
        '1': 'en',
        '2': 'to',
        '3': 'tre',
        '4': 'fire',
        '5': 'fem',
        '6': 'seks',
        '7': 'syv',
        '8': 'otte',
        '9': 'ni',
        '10': 'ti',
        '20': 'tyve',
        '30': 'tredive',
        '40': 'fyrre',
        '50': 'halvtreds',
        '100': 'hundrede',
        '1000': 'tusind',
      },
      sentences: {
        // Greetings
        Hello: 'Hej',
        'Good morning': 'God morgen',
        'Good afternoon': 'God eftermiddag',
        'Good night': 'God nat',
        Goodbye: 'Farvel',
        // Essential Phrases
        'How are you?': 'Hvordan har du det?',
        'I am fine': 'Jeg har det godt',
        'Thank you': 'Tak',
        "You're welcome": 'Selv tak',
        Please: 'Vær så venlig',
        'Excuse me': 'Undskyld',
        "I'm sorry": 'Jeg beklager',
        // Emergency Phrases
        'I need help': 'Jeg har brug for hjælp',
        'I am lost': 'Jeg er faret vild',
        "I don't understand": 'Jeg forstår ikke',
        'Do you speak English?': 'Taler du engelsk?',
        'Where is the bathroom?': 'Hvor er toilettet?',
        // Practical Phrases
        'How much does it cost?': 'Hvor meget koster det?',
        'Can you help me?': 'Kan du hjælpe mig?',
        'I would like...': 'Jeg vil gerne have...',
        'The check, please': 'Regningen, tak',
      },
    },
    sv: {
      words: {
        // Essential Nouns
        water: 'vatten',
        food: 'mat',
        restaurant: 'restaurang',
        bathroom: 'toalett',
        hospital: 'sjukhus',
        hotel: 'hotell',
        airport: 'flygplats',
        train: 'tåg',
        bus: 'buss',
        taxi: 'taxi',
        // Common Adjectives
        good: 'bra',
        bad: 'dålig',
        big: 'stor',
        small: 'liten',
        hot: 'varm',
        cold: 'kall',
        // Essential Verbs
        'to eat': 'äta',
        'to drink': 'dricka',
        'to sleep': 'sova',
        'to go': 'gå',
        'to help': 'hjälpa',
        thanks: 'tack',
      },
      numbers: {
        '0': 'noll',
        '1': 'ett',
        '2': 'två',
        '3': 'tre',
        '4': 'fyra',
        '5': 'fem',
        '6': 'sex',
        '7': 'sju',
        '8': 'åtta',
        '9': 'nio',
        '10': 'tio',
        '20': 'tjugo',
        '30': 'trettio',
        '40': 'fyrtio',
        '50': 'femtio',
        '100': 'hundra',
        '1000': 'tusen',
      },
      sentences: {
        // Greetings
        Hello: 'Hej',
        'Good morning': 'God morgon',
        'Good afternoon': 'God eftermiddag',
        'Good night': 'God natt',
        Goodbye: 'Hejdå',
        // Essential Phrases
        'How are you?': 'Hur mår du?',
        'I am fine': 'Jag mår bra',
        'Thank you': 'Tack',
        "You're welcome": 'Varsågod',
        Please: 'Snälla',
        'Excuse me': 'Ursäkta',
        "I'm sorry": 'Förlåt',
        // Emergency Phrases
        'I need help': 'Jag behöver hjälp',
        'I am lost': 'Jag har gått vilse',
        "I don't understand": 'Jag förstår inte',
        'Do you speak English?': 'Pratar du engelska?',
        'Where is the bathroom?': 'Var finns toaletten?',
        // Practical Phrases
        'How much does it cost?': 'Hur mycket kostar det?',
        'Can you help me?': 'Kan du hjälpa mig?',
        'I would like...': 'Jag skulle vilja ha...',
        'The check, please': 'Notan, tack',
      },
    },

    nl: {
      words: {
        // Essential Nouns
        water: 'Water',
        food: 'Eten',
        restaurant: 'Restaurant',
        bathroom: 'Toilet',
        hospital: 'Ziekenhuis',
        hotel: 'Hotel',
        airport: 'Vliegveld',
        train: 'Trein',
        bus: 'Bus',
        taxi: 'Taxi',
        // Common Adjectives
        good: 'goed',
        bad: 'slecht',
        big: 'groot',
        small: 'klein',
        hot: 'heet',
        cold: 'koud',
        // Essential Verbs
        'to eat': 'eten',
        'to drink': 'drinken',
        'to sleep': 'slapen',
        'to go': 'gaan',
        'to help': 'helpen',
        thanks: 'dank je',
      },
      numbers: {
        '0': 'nul',
        '1': 'één',
        '2': 'twee',
        '3': 'drie',
        '4': 'vier',
        '5': 'vijf',
        '6': 'zes',
        '7': 'zeven',
        '8': 'acht',
        '9': 'negen',
        '10': 'tien',
        '20': 'twintig',
        '30': 'dertig',
        '40': 'veertig',
        '50': 'vijftig',
        '100': 'honderd',
        '1000': 'duizend',
      },
      sentences: {
        // Greetings
        Hello: 'Hallo',
        'Good morning': 'Goedemorgen',
        'Good afternoon': 'Goedemiddag',
        'Good night': 'Goedenacht',
        Goodbye: 'Vaarwel',
        // Essential Phrases
        'How are you?': 'Hoe gaat het met je?',
        'I am fine': 'Het gaat goed met mij',
        'Thank you': 'Dank je',
        "You're welcome": 'Graag gedaan',
        Please: 'Alsjeblieft',
        'Excuse me': 'Excuseer mij',
        "I'm sorry": 'Het spijt me',
        // Emergency Phrases
        'I need help': 'Ik heb hulp nodig',
        'I am lost': 'Ik ben verdwaald',
        "I don't understand": 'Ik begrijp het niet',
        'Do you speak English?': 'Spreek je Engels?',
        'Where is the bathroom?': 'Waar is de wc?',
        // Practical Phrases
        'How much does it cost?': 'Hoeveel kost het?',
        'Can you help me?': 'Kun je mij helpen?',
        'I would like...': 'Ik wil graag...',
        'The check, please': 'De rekening, alsjeblieft',
      },
    },
    tr: {
      words: {
        // Essential Nouns
        water: 'su',
        food: 'yemek',
        restaurant: 'lokanta',
        bathroom: 'tuvalet',
        hospital: 'hastane',
        hotel: 'otel',
        airport: 'havalimanı',
        train: 'tren',
        bus: 'otobüs',
        taxi: 'taksi',
        // Common Adjectives
        good: 'iyi',
        bad: 'kötü',
        big: 'büyük',
        small: 'küçük',
        hot: 'sıcak',
        cold: 'soğuk',
        // Essential Verbs
        'to eat': 'yemek',
        'to drink': 'içmek',
        'to sleep': 'uyumak',
        'to go': 'gitmek',
        'to help': 'yardım etmek',
        thanks: 'teşekkürler',
      },
      numbers: {
        '0': 'sıfır',
        '1': 'bir',
        '2': 'iki',
        '3': 'üç',
        '4': 'dört',
        '5': 'beş',
        '6': 'altı',
        '7': 'yedi',
        '8': 'sekiz',
        '9': 'dokuz',
        '10': 'on',
        '20': 'yirmi',
        '30': 'otuz',
        '40': 'kırk',
        '50': 'elli',
        '100': 'yüz',
        '1000': 'bin',
      },
      sentences: {
        // Greetings
        Hello: 'Merhaba',
        'Good morning': 'Günaydın',
        'Good afternoon': 'İyi günler',
        'Good night': 'İyi geceler',
        Goodbye: 'Hoşça kal',
        // Essential Phrases
        'How are you?': 'Nasılsın?',
        'I am fine': 'İyiyim',
        'Thank you': 'Teşekkür ederim',
        "You're welcome": 'Rica ederim',
        Please: 'Lütfen',
        'Excuse me': 'Özür dilerim',
        "I'm sorry": 'Üzgünüm',
        // Emergency Phrases
        'I need help': 'Yardıma ihtiyacım var',
        'I am lost': 'Kayboldum',
        "I don't understand": 'Anlamıyorum',
        'Do you speak English?': 'İngilizce biliyor musunuz?',
        'Where is the bathroom?': 'Tuvalet nerede?',
        // Practical Phrases
        'How much does it cost?': 'Ne kadar?',
        'Can you help me?': 'Bana yardım edebilir misiniz?',
        'I would like...': 'İstiyorum...',
        'The check, please': 'Hesap, lütfen',
      },
    },
    ro: {
      words: {
        // Essential Nouns
        water: 'apă',
        food: 'mâncare',
        restaurant: 'restaurant',
        bathroom: 'baie',
        hospital: 'spital',
        hotel: 'hotel',
        airport: 'aeroport',
        train: 'tren',
        bus: 'autobuz',
        taxi: 'taxi',
        // Common Adjectives
        good: 'bun',
        bad: 'rău',
        big: 'mare',
        small: 'mic',
        hot: 'cald',
        cold: 'rece',
        // Essential Verbs
        'to eat': 'a mânca',
        'to drink': 'a bea',
        'to sleep': 'a dormi',
        'to go': 'a merge',
        'to help': 'a ajuta',
        thanks: 'mulțumesc',
      },
      numbers: {
        '0': 'zero',
        '1': 'unu',
        '2': 'doi',
        '3': 'trei',
        '4': 'patru',
        '5': 'cinci',
        '6': 'șase',
        '7': 'șapte',
        '8': 'opt',
        '9': 'nouă',
        '10': 'zece',
        '20': 'douăzeci',
        '30': 'treizeci',
        '40': 'patruzeci',
        '50': 'cincizeci',
        '100': 'sută',
        '1000': 'mie',
      },
      sentences: {
        // Greetings
        Hello: 'Bună',
        'Good morning': 'Bună dimineața',
        'Good afternoon': 'Bună ziua',
        'Good night': 'Noapte bună',
        Goodbye: 'La revedere',
        // Essential Phrases
        'How are you?': 'Ce mai faci?',
        'I am fine': 'Sunt bine',
        'Thank you': 'Mulțumesc',
        "You're welcome": 'Cu plăcere',
        Please: 'Te rog',
        'Excuse me': 'Scuză-mă',
        "I'm sorry": 'Îmi pare rău',
        // Emergency Phrases
        'I need help': 'Am nevoie de ajutor',
        'I am lost': 'M-am pierdut',
        "I don't understand": 'Nu înțeleg',
        'Do you speak English?': 'Vorbiți engleză?',
        'Where is the bathroom?': 'Unde este baia?',
        // Practical Phrases
        'How much does it cost?': 'Cât costă?',
        'Can you help me?': 'Mă puteți ajuta?',
        'I would like...': 'Aș dori...',
        'The check, please': 'Nota de plată, vă rog',
      },
    },
    is: {
      words: {
        // Essential Nouns
        water: 'vatn',
        food: 'matur',
        restaurant: 'veitingastaður',
        bathroom: 'baðherbergi',
        hospital: 'sjúkrahús',
        hotel: 'hótel',
        airport: 'flugvöllur',
        train: 'lest',
        bus: 'strætó',
        taxi: 'leigubíll',
        // Common Adjectives
        good: 'góður',
        bad: 'slæmur',
        big: 'stór',
        small: 'lítill',
        hot: 'heitur',
        cold: 'kaldur',
        // Essential Verbs
        'to eat': 'að borða',
        'to drink': 'að drekka',
        'to sleep': 'að sofa',
        'to go': 'að fara',
        'to help': 'að hjálpa',
        thanks: 'takk',
      },
      numbers: {
        '0': 'núll',
        '1': 'einn',
        '2': 'tveir',
        '3': 'þrír',
        '4': 'fjórir',
        '5': 'fimm',
        '6': 'sex',
        '7': 'sjö',
        '8': 'átta',
        '9': 'níu',
        '10': 'tíu',
        '20': 'tuttugu',
        '30': 'þrjátíu',
        '40': 'fjörutíu',
        '50': 'fimmtíu',
        '100': 'hundrað',
        '1000': 'þúsund',
      },
      sentences: {
        // Greetings
        Hello: 'Halló',
        'Good morning': 'Góðan daginn',
        'Good afternoon': 'Góðan daginn',
        'Good night': 'Góða nótt',
        Goodbye: 'Vertu sæll',
        // Essential Phrases
        'How are you?': 'Hvernig hefurðu það?',
        'I am fine': 'Mér líður vel',
        'Thank you': 'Takk fyrir',
        "You're welcome": 'Verði þér að góðu',
        Please: 'Gjörðu svo vel',
        'Excuse me': 'Afsakið',
        "I'm sorry": 'Fyrirgefðu',
        // Emergency Phrases
        'I need help': 'Ég þarf hjálp',
        'I am lost': 'Ég er villtur',
        "I don't understand": 'Ég skil ekki',
        'Do you speak English?': 'Talarðu ensku?',
        'Where is the bathroom?': 'Hvar er klósettið?',
        // Practical Phrases
        'How much does it cost?': 'Hvað kostar þetta?',
        'Can you help me?': 'Geturðu hjálpað mér?',
        'I would like...': 'Ég vildi gjarnan...',
        'The check, please': 'Reikninginn, takk',
      },
    },
    pt: {
      words: {
        // Essential Nouns
        water: 'água',
        food: 'comida',
        restaurant: 'restaurante',
        bathroom: 'banheiro',
        hospital: 'hospital',
        hotel: 'hotel',
        airport: 'aeroporto',
        train: 'trem',
        bus: 'ônibus',
        taxi: 'táxi',
        // Common Adjectives
        good: 'bom',
        bad: 'mau',
        big: 'grande',
        small: 'pequeno',
        hot: 'quente',
        cold: 'frio',
        // Essential Verbs
        'to eat': 'comer',
        'to drink': 'beber',
        'to sleep': 'dormir',
        'to go': 'ir',
        'to help': 'ajudar',
        thanks: 'obrigado',
      },
      numbers: {
        '0': 'zero',
        '1': 'um',
        '2': 'dois',
        '3': 'três',
        '4': 'quatro',
        '5': 'cinco',
        '6': 'seis',
        '7': 'sete',
        '8': 'oito',
        '9': 'nove',
        '10': 'dez',
        '20': 'vinte',
        '30': 'trinta',
        '40': 'quarenta',
        '50': 'cinquenta',
        '100': 'cem',
        '1000': 'mil',
      },
      sentences: {
        // Greetings
        Hello: 'Olá',
        'Good morning': 'Bom dia',
        'Good afternoon': 'Boa tarde',
        'Good night': 'Boa noite',
        Goodbye: 'Adeus',
        // Essential Phrases
        'How are you?': 'Como está?',
        'I am fine': 'Estou bem',
        'Thank you': 'Obrigado',
        "You're welcome": 'De nada',
        Please: 'Por favor',
        'Excuse me': 'Com licença',
        "I'm sorry": 'Desculpe',
        // Emergency Phrases
        'I need help': 'Preciso de ajuda',
        'I am lost': 'Estou perdido',
        "I don't understand": 'Não entendo',
        'Do you speak English?': 'Você fala inglês?',
        'Where is the bathroom?': 'Onde é o banheiro?',
        // Practical Phrases
        'How much does it cost?': 'Quanto custa?',
        'Can you help me?': 'Pode me ajudar?',
        'I would like...': 'Eu gostaria...',
        'The check, please': 'A conta, por favor',
      },
    },
    cy: {
      words: {
        // Essential Nouns
        water: 'dŵr',
        food: 'bwyd',
        restaurant: 'bwyty',
        bathroom: 'ystafell ymolchi',
        hospital: 'ysbyty',
        hotel: 'gwesty',
        airport: 'maes awyr',
        train: 'trên',
        bus: 'bws',
        taxi: 'tacsi',
        // Common Adjectives
        good: 'da',
        bad: 'drwg',
        big: 'mawr',
        small: 'bach',
        hot: 'poeth',
        cold: 'oer',
        // Essential Verbs
        'to eat': 'bwyta',
        'to drink': 'yfed',
        'to sleep': 'cysgu',
        'to go': 'mynd',
        'to help': 'helpu',
        thanks: 'diolch',
      },
      numbers: {
        '0': 'sero',
        '1': 'un',
        '2': 'dau',
        '3': 'tri',
        '4': 'pedwar',
        '5': 'pump',
        '6': 'chwech',
        '7': 'saith',
        '8': 'wyth',
        '9': 'naw',
        '10': 'deg',
        '20': 'ugain',
        '30': 'deg ar hugain',
        '40': 'deugain',
        '50': 'hanner cant',
        '100': 'cant',
        '1000': 'mil',
      },
      sentences: {
        // Greetings
        Hello: 'Helo',
        'Good morning': 'Bore da',
        'Good afternoon': 'Prynhawn da',
        'Good night': 'Nos da',
        Goodbye: 'Hwyl fawr',
        // Essential Phrases
        'How are you?': 'Sut wyt ti?',
        'I am fine': "Dw i'n iawn",
        'Thank you': 'Diolch',
        "You're welcome": 'Croeso',
        Please: 'Os gwelwch yn dda',
        'Excuse me': 'Esgusodwch fi',
        "I'm sorry": "Mae'n ddrwg gen i",
        // Emergency Phrases
        'I need help': 'Dw i angen help',
        'I am lost': 'Dw i ar goll',
        "I don't understand": 'Dw i ddim yn deall',
        'Do you speak English?': "Ydych chi'n siarad Saesneg?",
        'Where is the bathroom?': "Ble mae'r ystafell ymolchi?",
        // Practical Phrases
        'How much does it cost?': 'Faint ydy o?',
        'Can you help me?': 'Allwch chi fy helpu i?',
        'I would like...': 'Hoffwn i...',
        'The check, please': 'Y bil, os gwelwch yn dda',
      },
    },
  };

  getLanguages(): Language[] {
    return [...this.languages].sort((a, b) => a.name.localeCompare(b.name));
  }

  getContent(languageCode: string): LearningContent | undefined {
    return this.content[languageCode];
  }
}
