import type { LearningContent } from './language.service';

export const PREMIUM_WORD_KEYS = [
  'I',
  'you',
  'friend',
  'family',
  'name',
  'today',
  'tomorrow',
  'now',
  'city',
  'street',
  'shop',
  'pharmacy',
  'police',
  'ticket',
  'coffee',
  'bread',
  'beer',
  'left',
  'right',
  'near',
  'cheap',
  'expensive',
  'open',
  'closed',
  'to want',
  'to buy',
  'to pay',
] as const;

export const PREMIUM_NUMBER_KEYS = [
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '60',
  '70',
  '80',
  '90',
  '200',
  '500',
] as const;

export const PREMIUM_SENTENCE_KEYS = [
  "What's your name?",
  'My name is...',
  'Where is the hotel?',
  'Where is the airport?',
  'I speak a little',
  'Do you have wifi?',
  'I have a reservation',
  "I'm allergic to...",
  'How do I get to...?',
  'Can I pay by card?',
  'Where can I buy a ticket?',
  'What time is it?',
  'See you later',
  'I need a taxi',
  'Is there a pharmacy nearby?',
  'Call a doctor',
  'I would like water',
  'Is this vegetarian?',
] as const;

export function mergeLearningContent(
  base: LearningContent,
  extra?: LearningContent
): LearningContent {
  if (!extra) {
    return {
      words: { ...base.words },
      numbers: { ...base.numbers },
      sentences: { ...base.sentences },
    };
  }

  return {
    words: { ...base.words, ...extra.words },
    numbers: { ...base.numbers, ...extra.numbers },
    sentences: { ...base.sentences, ...extra.sentences },
  };
}

export const PREMIUM_CONTENT: { [key: string]: LearningContent } = {
  en: {
    words: {
      I: 'I',
      you: 'you',
      friend: 'friend',
      family: 'family',
      name: 'name',
      today: 'today',
      tomorrow: 'tomorrow',
      now: 'now',
      city: 'city',
      street: 'street',
      shop: 'shop',
      pharmacy: 'pharmacy',
      police: 'police',
      ticket: 'ticket',
      coffee: 'coffee',
      bread: 'bread',
      beer: 'beer',
      left: 'left',
      right: 'right',
      near: 'near',
      cheap: 'cheap',
      expensive: 'expensive',
      open: 'open',
      closed: 'closed',
      'to want': 'to want',
      'to buy': 'to buy',
      'to pay': 'to pay',
    },
    numbers: {
      '11': 'eleven',
      '12': 'twelve',
      '13': 'thirteen',
      '14': 'fourteen',
      '15': 'fifteen',
      '16': 'sixteen',
      '17': 'seventeen',
      '18': 'eighteen',
      '19': 'nineteen',
      '60': 'sixty',
      '70': 'seventy',
      '80': 'eighty',
      '90': 'ninety',
      '200': 'two hundred',
      '500': 'five hundred',
    },
    sentences: {
      "What's your name?": "What's your name?",
      'My name is...': 'My name is...',
      'Where is the hotel?': 'Where is the hotel?',
      'Where is the airport?': 'Where is the airport?',
      'I speak a little': 'I speak a little',
      'Do you have wifi?': 'Do you have wifi?',
      'I have a reservation': 'I have a reservation',
      "I'm allergic to...": "I'm allergic to...",
      'How do I get to...?': 'How do I get to...?',
      'Can I pay by card?': 'Can I pay by card?',
      'Where can I buy a ticket?': 'Where can I buy a ticket?',
      'What time is it?': 'What time is it?',
      'See you later': 'See you later',
      'I need a taxi': 'I need a taxi',
      'Is there a pharmacy nearby?': 'Is there a pharmacy nearby?',
      'Call a doctor': 'Call a doctor',
      'I would like water': 'I would like water',
      'Is this vegetarian?': 'Is this vegetarian?',
    },
  },
  no: {
    words: {
      I: 'jeg',
      you: 'du',
      friend: 'venn',
      family: 'familie',
      name: 'navn',
      today: 'i dag',
      tomorrow: 'i morgen',
      now: 'nå',
      city: 'by',
      street: 'gate',
      shop: 'butikk',
      pharmacy: 'apotek',
      police: 'politi',
      ticket: 'billett',
      coffee: 'kaffe',
      bread: 'brød',
      beer: 'øl',
      left: 'venstre',
      right: 'høyre',
      near: 'nær',
      cheap: 'billig',
      expensive: 'dyr',
      open: 'åpen',
      closed: 'stengt',
      'to want': 'å ville',
      'to buy': 'å kjøpe',
      'to pay': 'å betale',
    },
    numbers: {
      '11': 'elleve',
      '12': 'tolv',
      '13': 'tretten',
      '14': 'fjorten',
      '15': 'femten',
      '16': 'seksten',
      '17': 'sytten',
      '18': 'atten',
      '19': 'nitten',
      '60': 'seksti',
      '70': 'sytti',
      '80': 'åtti',
      '90': 'nitti',
      '200': 'to hundre',
      '500': 'fem hundre',
    },
    sentences: {
      "What's your name?": 'Hva heter du?',
      'My name is...': 'Jeg heter...',
      'Where is the hotel?': 'Hvor er hotellet?',
      'Where is the airport?': 'Hvor er flyplassen?',
      'I speak a little': 'Jeg snakker litt',
      'Do you have wifi?': 'Har dere wifi?',
      'I have a reservation': 'Jeg har en reservasjon',
      "I'm allergic to...": 'Jeg er allergisk mot...',
      'How do I get to...?': 'Hvordan kommer jeg til...?',
      'Can I pay by card?': 'Kan jeg betale med kort?',
      'Where can I buy a ticket?': 'Hvor kan jeg kjøpe billett?',
      'What time is it?': 'Hva er klokka?',
      'See you later': 'Vi ses',
      'I need a taxi': 'Jeg trenger en taxi',
      'Is there a pharmacy nearby?': 'Er det et apotek i nærheten?',
      'Call a doctor': 'Ring en lege',
      'I would like water': 'Jeg vil gjerne ha vann',
      'Is this vegetarian?': 'Er dette vegetarisk?',
    },
  },
  es: {
    words: {
      I: 'yo',
      you: 'tú',
      friend: 'amigo',
      family: 'familia',
      name: 'nombre',
      today: 'hoy',
      tomorrow: 'mañana',
      now: 'ahora',
      city: 'ciudad',
      street: 'calle',
      shop: 'tienda',
      pharmacy: 'farmacia',
      police: 'policía',
      ticket: 'billete',
      coffee: 'café',
      bread: 'pan',
      beer: 'cerveza',
      left: 'izquierda',
      right: 'derecha',
      near: 'cerca',
      cheap: 'barato',
      expensive: 'caro',
      open: 'abierto',
      closed: 'cerrado',
      'to want': 'querer',
      'to buy': 'comprar',
      'to pay': 'pagar',
    },
    numbers: {
      '11': 'once',
      '12': 'doce',
      '13': 'trece',
      '14': 'catorce',
      '15': 'quince',
      '16': 'dieciséis',
      '17': 'diecisiete',
      '18': 'dieciocho',
      '19': 'diecinueve',
      '60': 'sesenta',
      '70': 'setenta',
      '80': 'ochenta',
      '90': 'noventa',
      '200': 'doscientos',
      '500': 'quinientos',
    },
    sentences: {
      "What's your name?": '¿Cómo te llamas?',
      'My name is...': 'Me llamo...',
      'Where is the hotel?': '¿Dónde está el hotel?',
      'Where is the airport?': '¿Dónde está el aeropuerto?',
      'I speak a little': 'Hablo un poco',
      'Do you have wifi?': '¿Tienen wifi?',
      'I have a reservation': 'Tengo una reserva',
      "I'm allergic to...": 'Soy alérgico a...',
      'How do I get to...?': '¿Cómo llego a...?',
      'Can I pay by card?': '¿Puedo pagar con tarjeta?',
      'Where can I buy a ticket?': '¿Dónde puedo comprar un billete?',
      'What time is it?': '¿Qué hora es?',
      'See you later': 'Hasta luego',
      'I need a taxi': 'Necesito un taxi',
      'Is there a pharmacy nearby?': '¿Hay una farmacia cerca?',
      'Call a doctor': 'Llame a un médico',
      'I would like water': 'Quisiera agua',
      'Is this vegetarian?': '¿Esto es vegetariano?',
    },
  },
  fr: {
    words: {
      I: 'je',
      you: 'tu',
      friend: 'ami',
      family: 'famille',
      name: 'nom',
      today: "aujourd'hui",
      tomorrow: 'demain',
      now: 'maintenant',
      city: 'ville',
      street: 'rue',
      shop: 'magasin',
      pharmacy: 'pharmacie',
      police: 'police',
      ticket: 'billet',
      coffee: 'café',
      bread: 'pain',
      beer: 'bière',
      left: 'gauche',
      right: 'droite',
      near: 'près',
      cheap: 'bon marché',
      expensive: 'cher',
      open: 'ouvert',
      closed: 'fermé',
      'to want': 'vouloir',
      'to buy': 'acheter',
      'to pay': 'payer',
    },
    numbers: {
      '11': 'onze',
      '12': 'douze',
      '13': 'treize',
      '14': 'quatorze',
      '15': 'quinze',
      '16': 'seize',
      '17': 'dix-sept',
      '18': 'dix-huit',
      '19': 'dix-neuf',
      '60': 'soixante',
      '70': 'soixante-dix',
      '80': 'quatre-vingts',
      '90': 'quatre-vingt-dix',
      '200': 'deux cents',
      '500': 'cinq cents',
    },
    sentences: {
      "What's your name?": 'Comment vous appelez-vous ?',
      'My name is...': "Je m'appelle...",
      'Where is the hotel?': "Où est l'hôtel ?",
      'Where is the airport?': "Où est l'aéroport ?",
      'I speak a little': 'Je parle un peu',
      'Do you have wifi?': 'Avez-vous le wifi ?',
      'I have a reservation': "J'ai une réservation",
      "I'm allergic to...": 'Je suis allergique à...',
      'How do I get to...?': 'Comment aller à... ?',
      'Can I pay by card?': 'Puis-je payer par carte ?',
      'Where can I buy a ticket?': 'Où puis-je acheter un billet ?',
      'What time is it?': 'Quelle heure est-il ?',
      'See you later': 'À plus tard',
      'I need a taxi': "J'ai besoin d'un taxi",
      'Is there a pharmacy nearby?': 'Y a-t-il une pharmacie à proximité ?',
      'Call a doctor': 'Appelez un médecin',
      'I would like water': "Je voudrais de l'eau",
      'Is this vegetarian?': 'Est-ce végétarien ?',
    },
  },
  de: {
    words: {
      I: 'ich',
      you: 'du',
      friend: 'Freund',
      family: 'Familie',
      name: 'Name',
      today: 'heute',
      tomorrow: 'morgen',
      now: 'jetzt',
      city: 'Stadt',
      street: 'Straße',
      shop: 'Geschäft',
      pharmacy: 'Apotheke',
      police: 'Polizei',
      ticket: 'Ticket',
      coffee: 'Kaffee',
      bread: 'Brot',
      beer: 'Bier',
      left: 'links',
      right: 'rechts',
      near: 'nah',
      cheap: 'billig',
      expensive: 'teuer',
      open: 'offen',
      closed: 'geschlossen',
      'to want': 'wollen',
      'to buy': 'kaufen',
      'to pay': 'bezahlen',
    },
    numbers: {
      '11': 'elf',
      '12': 'zwölf',
      '13': 'dreizehn',
      '14': 'vierzehn',
      '15': 'fünfzehn',
      '16': 'sechzehn',
      '17': 'siebzehn',
      '18': 'achtzehn',
      '19': 'neunzehn',
      '60': 'sechzig',
      '70': 'siebzig',
      '80': 'achtzig',
      '90': 'neunzig',
      '200': 'zweihundert',
      '500': 'fünfhundert',
    },
    sentences: {
      "What's your name?": 'Wie heißen Sie?',
      'My name is...': 'Ich heiße...',
      'Where is the hotel?': 'Wo ist das Hotel?',
      'Where is the airport?': 'Wo ist der Flughafen?',
      'I speak a little': 'Ich spreche ein wenig',
      'Do you have wifi?': 'Haben Sie WLAN?',
      'I have a reservation': 'Ich habe eine Reservierung',
      "I'm allergic to...": 'Ich bin allergisch gegen...',
      'How do I get to...?': 'Wie komme ich zu...?',
      'Can I pay by card?': 'Kann ich mit Karte zahlen?',
      'Where can I buy a ticket?': 'Wo kann ich ein Ticket kaufen?',
      'What time is it?': 'Wie spät ist es?',
      'See you later': 'Bis später',
      'I need a taxi': 'Ich brauche ein Taxi',
      'Is there a pharmacy nearby?': 'Gibt es eine Apotheke in der Nähe?',
      'Call a doctor': 'Rufen Sie einen Arzt',
      'I would like water': 'Ich hätte gern Wasser',
      'Is this vegetarian?': 'Ist das vegetarisch?',
    },
  },
  it: {
    words: {
      I: 'io',
      you: 'tu',
      friend: 'amico',
      family: 'famiglia',
      name: 'nome',
      today: 'oggi',
      tomorrow: 'domani',
      now: 'adesso',
      city: 'città',
      street: 'strada',
      shop: 'negozio',
      pharmacy: 'farmacia',
      police: 'polizia',
      ticket: 'biglietto',
      coffee: 'caffè',
      bread: 'pane',
      beer: 'birra',
      left: 'sinistra',
      right: 'destra',
      near: 'vicino',
      cheap: 'economico',
      expensive: 'costoso',
      open: 'aperto',
      closed: 'chiuso',
      'to want': 'volere',
      'to buy': 'comprare',
      'to pay': 'pagare',
    },
    numbers: {
      '11': 'undici',
      '12': 'dodici',
      '13': 'tredici',
      '14': 'quattordici',
      '15': 'quindici',
      '16': 'sedici',
      '17': 'diciassette',
      '18': 'diciotto',
      '19': 'diciannove',
      '60': 'sessanta',
      '70': 'settanta',
      '80': 'ottanta',
      '90': 'novanta',
      '200': 'duecento',
      '500': 'cinquecento',
    },
    sentences: {
      "What's your name?": 'Come ti chiami?',
      'My name is...': 'Mi chiamo...',
      'Where is the hotel?': "Dov'è l'hotel?",
      'Where is the airport?': "Dov'è l'aeroporto?",
      'I speak a little': 'Parlo un po\'',
      'Do you have wifi?': 'Avete il wifi?',
      'I have a reservation': 'Ho una prenotazione',
      "I'm allergic to...": 'Sono allergico a...',
      'How do I get to...?': 'Come arrivo a...?',
      'Can I pay by card?': 'Posso pagare con la carta?',
      'Where can I buy a ticket?': 'Dove posso comprare un biglietto?',
      'What time is it?': 'Che ore sono?',
      'See you later': 'A dopo',
      'I need a taxi': 'Ho bisogno di un taxi',
      'Is there a pharmacy nearby?': "C'è una farmacia qui vicino?",
      'Call a doctor': 'Chiami un medico',
      'I would like water': "Vorrei dell'acqua",
      'Is this vegetarian?': 'È vegetariano?',
    },
  },
  ja: {
    words: {
      I: '私 (watashi)',
      you: 'あなた (anata)',
      friend: '友達 (tomodachi)',
      family: '家族 (kazoku)',
      name: '名前 (namae)',
      today: '今日 (kyō)',
      tomorrow: '明日 (ashita)',
      now: '今 (ima)',
      city: '市 (shi)',
      street: '通り (tōri)',
      shop: '店 (mise)',
      pharmacy: '薬局 (yakkyoku)',
      police: '警察 (keisatsu)',
      ticket: '切符 (kippu)',
      coffee: 'コーヒー (kōhī)',
      bread: 'パン (pan)',
      beer: 'ビール (bīru)',
      left: '左 (hidari)',
      right: '右 (migi)',
      near: '近い (chikai)',
      cheap: '安い (yasui)',
      expensive: '高い (takai)',
      open: '開いている (aite iru)',
      closed: '閉まっている (shimatte iru)',
      'to want': '欲しい (hoshii)',
      'to buy': '買う (kau)',
      'to pay': '払う (harau)',
    },
    numbers: {
      '11': '十一 (jūichi)',
      '12': '十二 (jūni)',
      '13': '十三 (jūsan)',
      '14': '十四 (jūyon)',
      '15': '十五 (jūgo)',
      '16': '十六 (jūroku)',
      '17': '十七 (jūnana)',
      '18': '十八 (jūhachi)',
      '19': '十九 (jūkyū)',
      '60': '六十 (rokujū)',
      '70': '七十 (nanajū)',
      '80': '八十 (hachijū)',
      '90': '九十 (kyūjū)',
      '200': '二百 (nihyaku)',
      '500': '五百 (gohyaku)',
    },
    sentences: {
      "What's your name?": 'お名前は何ですか？ (O-namae wa nan desu ka?)',
      'My name is...': '私の名前は...です (Watashi no namae wa... desu)',
      'Where is the hotel?': 'ホテルはどこですか？ (Hoteru wa doko desu ka?)',
      'Where is the airport?': '空港はどこですか？ (Kūkō wa doko desu ka?)',
      'I speak a little': '少し話せます (Sukoshi hanasemasu)',
      'Do you have wifi?': 'Wi-Fiはありますか？ (Wi-Fi wa arimasu ka?)',
      'I have a reservation': '予約しています (Yoyaku shite imasu)',
      "I'm allergic to...": '...にアレルギーがあります (...ni arerugī ga arimasu)',
      'How do I get to...?': '...へはどう行きますか？ (...e wa dō ikimasu ka?)',
      'Can I pay by card?': 'カードで払えますか？ (Kādo de haraemasu ka?)',
      'Where can I buy a ticket?':
        '切符はどこで買えますか？ (Kippu wa doko de kaemasu ka?)',
      'What time is it?': '今何時ですか？ (Ima nanji desu ka?)',
      'See you later': 'またね (Mata ne)',
      'I need a taxi': 'タクシーが必要です (Takushī ga hitsuyō desu)',
      'Is there a pharmacy nearby?':
        '近くに薬局はありますか？ (Chikaku ni yakkyoku wa arimasu ka?)',
      'Call a doctor': '医者を呼んでください (Isha o yonde kudasai)',
      'I would like water': '水をお願いします (Mizu o onegaishimasu)',
      'Is this vegetarian?':
        'これはベジタリアンですか？ (Kore wa bejitarian desu ka?)',
    },
  },
  zh: {
    words: {
      I: '我 (wǒ)',
      you: '你 (nǐ)',
      friend: '朋友 (péngyou)',
      family: '家人 (jiārén)',
      name: '名字 (míngzi)',
      today: '今天 (jīntiān)',
      tomorrow: '明天 (míngtiān)',
      now: '现在 (xiànzài)',
      city: '城市 (chéngshì)',
      street: '街道 (jiēdào)',
      shop: '商店 (shāngdiàn)',
      pharmacy: '药房 (yàofáng)',
      police: '警察 (jǐngchá)',
      ticket: '票 (piào)',
      coffee: '咖啡 (kāfēi)',
      bread: '面包 (miànbāo)',
      beer: '啤酒 (píjiǔ)',
      left: '左 (zuǒ)',
      right: '右 (yòu)',
      near: '近 (jìn)',
      cheap: '便宜 (piányi)',
      expensive: '贵 (guì)',
      open: '开着 (kāizhe)',
      closed: '关着 (guānzhe)',
      'to want': '想要 (xiǎng yào)',
      'to buy': '买 (mǎi)',
      'to pay': '付 (fù)',
    },
    numbers: {
      '11': '十一 (shíyī)',
      '12': '十二 (shí\'èr)',
      '13': '十三 (shísān)',
      '14': '十四 (shísì)',
      '15': '十五 (shíwǔ)',
      '16': '十六 (shíliù)',
      '17': '十七 (shíqī)',
      '18': '十八 (shíbā)',
      '19': '十九 (shíjiǔ)',
      '60': '六十 (liùshí)',
      '70': '七十 (qīshí)',
      '80': '八十 (bāshí)',
      '90': '九十 (jiǔshí)',
      '200': '二百 (èrbǎi)',
      '500': '五百 (wǔbǎi)',
    },
    sentences: {
      "What's your name?": '你叫什么名字？(Nǐ jiào shénme míngzi?)',
      'My name is...': '我叫... (Wǒ jiào...)',
      'Where is the hotel?': '酒店在哪里？(Jiǔdiàn zài nǎli?)',
      'Where is the airport?': '机场在哪里？(Jīchǎng zài nǎli?)',
      'I speak a little': '我会说一点 (Wǒ huì shuō yīdiǎn)',
      'Do you have wifi?': '有无线网吗？(Yǒu wúxiànwǎng ma?)',
      'I have a reservation': '我有预订 (Wǒ yǒu yùdìng)',
      "I'm allergic to...": '我对...过敏 (Wǒ duì... guòmǐn)',
      'How do I get to...?': '去...怎么走？(Qù... zěnme zǒu?)',
      'Can I pay by card?': '可以刷卡吗？(Kěyǐ shuākǎ ma?)',
      'Where can I buy a ticket?': '在哪里可以买票？(Zài nǎli kěyǐ mǎi piào?)',
      'What time is it?': '现在几点？(Xiànzài jǐ diǎn?)',
      'See you later': '回头见 (Huítóu jiàn)',
      'I need a taxi': '我需要出租车 (Wǒ xūyào chūzūchē)',
      'Is there a pharmacy nearby?': '附近有药房吗？(Fùjìn yǒu yàofáng ma?)',
      'Call a doctor': '请叫医生 (Qǐng jiào yīshēng)',
      'I would like water': '我想要水 (Wǒ xiǎng yào shuǐ)',
      'Is this vegetarian?': '这是素的吗？(Zhè shì sù de ma?)',
    },
  },
  ko: {
    words: {
      I: '나 (na)',
      you: '당신 (dangsin)',
      friend: '친구 (chingu)',
      family: '가족 (gajok)',
      name: '이름 (ireum)',
      today: '오늘 (oneul)',
      tomorrow: '내일 (naeil)',
      now: '지금 (jigeum)',
      city: '도시 (dosi)',
      street: '거리 (geori)',
      shop: '가게 (gage)',
      pharmacy: '약국 (yakguk)',
      police: '경찰 (gyeongchal)',
      ticket: '표 (pyo)',
      coffee: '커피 (keopi)',
      bread: '빵 (ppang)',
      beer: '맥주 (maekju)',
      left: '왼쪽 (oenjjok)',
      right: '오른쪽 (oreunjjok)',
      near: '가까운 (gakkaun)',
      cheap: '싼 (ssan)',
      expensive: '비싼 (bissan)',
      open: '열린 (yeollin)',
      closed: '닫힌 (dachin)',
      'to want': '원하다 (wonhada)',
      'to buy': '사다 (sada)',
      'to pay': '지불하다 (jibulhada)',
    },
    numbers: {
      '11': '십일 (sibil)',
      '12': '십이 (sibi)',
      '13': '십삼 (sipsam)',
      '14': '십사 (sipsa)',
      '15': '십오 (sibo)',
      '16': '십육 (sipyuk)',
      '17': '십칠 (sipchil)',
      '18': '십팔 (sippal)',
      '19': '십구 (sipgu)',
      '60': '육십 (yuksip)',
      '70': '칠십 (chilsip)',
      '80': '팔십 (palsip)',
      '90': '구십 (gusip)',
      '200': '이백 (ibaek)',
      '500': '오백 (obaek)',
    },
    sentences: {
      "What's your name?": '이름이 뭐예요? (Ireum-i mwoyeyo?)',
      'My name is...': '제 이름은...입니다 (Je ireum-eun...imnida)',
      'Where is the hotel?': '호텔이 어디예요? (Hotel-i eodiyeyo?)',
      'Where is the airport?': '공항이 어디예요? (Gonghang-i eodiyeyo?)',
      'I speak a little': '조금 할 줄 알아요 (Jogeum hal jul arayo)',
      'Do you have wifi?': '와이파이 있나요? (Waipai innayo?)',
      'I have a reservation': '예약이 있어요 (Yeyak-i isseoyo)',
      "I'm allergic to...": '...에 알레르기가 있어요 (...e allereugi-ga isseoyo)',
      'How do I get to...?': '...에 어떻게 가요? (...e eotteoke gayo?)',
      'Can I pay by card?': '카드로 결제할 수 있나요? (Kadeuro gyeoljehal su innayo?)',
      'Where can I buy a ticket?': '표는 어디서 사요? (Pyo-neun eodiseo sayo?)',
      'What time is it?': '지금 몇 시예요? (Jigeum myeot siyeyo?)',
      'See you later': '나중에 봐요 (Najunge bwayo)',
      'I need a taxi': '택시가 필요해요 (Taeksi-ga pilyohaeyo)',
      'Is there a pharmacy nearby?':
        '근처에 약국 있나요? (Geuncheo-e yakguk innayo?)',
      'Call a doctor': '의사를 불러 주세요 (Uisa-reul bulleo juseyo)',
      'I would like water': '물 주세요 (Mul juseyo)',
      'Is this vegetarian?': '이거 채식이에요? (Igeo chaesigieyo?)',
    },
  },
  pl: {
    words: {
      I: 'ja',
      you: 'ty',
      friend: 'przyjaciel',
      family: 'rodzina',
      name: 'imię',
      today: 'dzisiaj',
      tomorrow: 'jutro',
      now: 'teraz',
      city: 'miasto',
      street: 'ulica',
      shop: 'sklep',
      pharmacy: 'apteka',
      police: 'policja',
      ticket: 'bilet',
      coffee: 'kawa',
      bread: 'chleb',
      beer: 'piwo',
      left: 'lewo',
      right: 'prawo',
      near: 'blisko',
      cheap: 'tani',
      expensive: 'drogi',
      open: 'otwarty',
      closed: 'zamknięty',
      'to want': 'chcieć',
      'to buy': 'kupić',
      'to pay': 'płacić',
    },
    numbers: {
      '11': 'jedenaście',
      '12': 'dwanaście',
      '13': 'trzynaście',
      '14': 'czternaście',
      '15': 'piętnaście',
      '16': 'szesnaście',
      '17': 'siedemnaście',
      '18': 'osiemnaście',
      '19': 'dziewiętnaście',
      '60': 'sześćdziesiąt',
      '70': 'siedemdziesiąt',
      '80': 'osiemdziesiąt',
      '90': 'dziewięćdziesiąt',
      '200': 'dwieście',
      '500': 'pięćset',
    },
    sentences: {
      "What's your name?": 'Jak masz na imię?',
      'My name is...': 'Nazywam się...',
      'Where is the hotel?': 'Gdzie jest hotel?',
      'Where is the airport?': 'Gdzie jest lotnisko?',
      'I speak a little': 'Mówię trochę',
      'Do you have wifi?': 'Czy macie wifi?',
      'I have a reservation': 'Mam rezerwację',
      "I'm allergic to...": 'Mam alergię na...',
      'How do I get to...?': 'Jak dojechać do...?',
      'Can I pay by card?': 'Czy mogę zapłacić kartą?',
      'Where can I buy a ticket?': 'Gdzie mogę kupić bilet?',
      'What time is it?': 'Która jest godzina?',
      'See you later': 'Do zobaczenia',
      'I need a taxi': 'Potrzebuję taksówki',
      'Is there a pharmacy nearby?': 'Czy jest tu apteka w pobliżu?',
      'Call a doctor': 'Proszę wezwać lekarza',
      'I would like water': 'Poproszę wodę',
      'Is this vegetarian?': 'Czy to jest wegetariańskie?',
    },
  },
  ru: {
    words: {
      I: 'я (ya)',
      you: 'ты (ty)',
      friend: 'друг (drug)',
      family: 'семья (semya)',
      name: 'имя (imya)',
      today: 'сегодня (segodnya)',
      tomorrow: 'завтра (zavtra)',
      now: 'сейчас (seychas)',
      city: 'город (gorod)',
      street: 'улица (ulitsa)',
      shop: 'магазин (magazin)',
      pharmacy: 'аптека (apteka)',
      police: 'полиция (politsiya)',
      ticket: 'билет (bilet)',
      coffee: 'кофе (kofe)',
      bread: 'хлеб (khleb)',
      beer: 'пиво (pivo)',
      left: 'лево (levo)',
      right: 'право (pravo)',
      near: 'близко (blizko)',
      cheap: 'дешёвый (deshovyy)',
      expensive: 'дорогой (dorogoy)',
      open: 'открыто (otkryto)',
      closed: 'закрыто (zakryto)',
      'to want': 'хотеть (khotet)',
      'to buy': 'покупать (pokupat)',
      'to pay': 'платить (platit)',
    },
    numbers: {
      '11': 'одиннадцать (odinnadtsat)',
      '12': 'двенадцать (dvenadtsat)',
      '13': 'тринадцать (trinadtsat)',
      '14': 'четырнадцать (chetyrnadtsat)',
      '15': 'пятнадцать (pyatnadtsat)',
      '16': 'шестнадцать (shestnadtsat)',
      '17': 'семнадцать (semnadtsat)',
      '18': 'восемнадцать (vosemnadtsat)',
      '19': 'девятнадцать (devyatnadtsat)',
      '60': 'шестьдесят (shestdesyat)',
      '70': 'семьдесят (semdesyat)',
      '80': 'восемьдесят (vosemdesyat)',
      '90': 'девяносто (devyanosto)',
      '200': 'двести (dvesti)',
      '500': 'пятьсот (pyatsot)',
    },
    sentences: {
      "What's your name?": 'Как вас зовут? (Kak vas zovut?)',
      'My name is...': 'Меня зовут... (Menya zovut...)',
      'Where is the hotel?': 'Где отель? (Gde otel?)',
      'Where is the airport?': 'Где аэропорт? (Gde aeroport?)',
      'I speak a little': 'Я немного говорю (Ya nemnogo govoryu)',
      'Do you have wifi?': 'У вас есть wifi? (U vas yest wifi?)',
      'I have a reservation': 'У меня есть бронь (U menya yest bron)',
      "I'm allergic to...": 'У меня аллергия на... (U menya allergiya na...)',
      'How do I get to...?': 'Как пройти к...? (Kak proyti k...?)',
      'Can I pay by card?': 'Можно оплатить картой? (Mozhno oplatit kartoy?)',
      'Where can I buy a ticket?':
        'Где можно купить билет? (Gde mozhno kupit bilet?)',
      'What time is it?': 'Который час? (Kotoryy chas?)',
      'See you later': 'До встречи (Do vstrechi)',
      'I need a taxi': 'Мне нужно такси (Mne nuzhno taksi)',
      'Is there a pharmacy nearby?':
        'Есть ли аптека поблизости? (Yest li apteka poblizosti?)',
      'Call a doctor': 'Вызовите врача (Vyzovite vracha)',
      'I would like water': 'Я бы хотел воды (Ya by khotel vody)',
      'Is this vegetarian?': 'Это вегетарианское? (Eto vegetarianskoe?)',
    },
  },
  me: {
    words: {
      I: 'ја (ja)',
      you: 'ти (ti)',
      friend: 'пријатељ (prijatelj)',
      family: 'породица (porodica)',
      name: 'име (ime)',
      today: 'данас (danas)',
      tomorrow: 'сутра (sutra)',
      now: 'сада (sada)',
      city: 'град (grad)',
      street: 'улица (ulica)',
      shop: 'продавница (prodavnica)',
      pharmacy: 'апотека (apoteka)',
      police: 'полиција (policija)',
      ticket: 'карта (karta)',
      coffee: 'кафа (kafa)',
      bread: 'хљеб (hljeb)',
      beer: 'пиво (pivo)',
      left: 'лијево (lijevo)',
      right: 'десно (desno)',
      near: 'близу (blizu)',
      cheap: 'јефтино (jeftino)',
      expensive: 'скупо (skupo)',
      open: 'отворено (otvoreno)',
      closed: 'затворено (zatvoreno)',
      'to want': 'хтјети (htjeti)',
      'to buy': 'купити (kupiti)',
      'to pay': 'платити (platiti)',
    },
    numbers: {
      '11': 'једанаест (jedanaest)',
      '12': 'дванаест (dvanaest)',
      '13': 'тринаест (trinaest)',
      '14': 'четрнаест (četrnaest)',
      '15': 'петнаест (petnaest)',
      '16': 'шеснаест (šesnaest)',
      '17': 'седамнаест (sedamnaest)',
      '18': 'осамнаест (osamnaest)',
      '19': 'деветнаест (devetnaest)',
      '60': 'шездесет (šezdeset)',
      '70': 'седамдесет (sedamdeset)',
      '80': 'осамдесет (osamdeset)',
      '90': 'деведесет (devedeset)',
      '200': 'двијеста (dvijesta)',
      '500': 'петсто (petsto)',
    },
    sentences: {
      "What's your name?": 'Како се зовеш? (Kako se zoveš?)',
      'My name is...': 'Зовем се... (Zovem se...)',
      'Where is the hotel?': 'Гдје је хотел? (Gdje je hotel?)',
      'Where is the airport?': 'Гдје је аеродром? (Gdje je aerodrom?)',
      'I speak a little': 'Говорим мало (Govorim malo)',
      'Do you have wifi?': 'Имате ли wifi? (Imate li wifi?)',
      'I have a reservation': 'Имам резервацију (Imam rezervaciju)',
      "I'm allergic to...": 'Алергичан сам на... (Alergičan sam na...)',
      'How do I get to...?': 'Како да дођем до...? (Kako da dođem do...?)',
      'Can I pay by card?': 'Могу ли платити картицом? (Mogu li platiti karticom?)',
      'Where can I buy a ticket?':
        'Гдје могу купити карту? (Gdje mogu kupiti kartu?)',
      'What time is it?': 'Колико је сати? (Koliko je sati?)',
      'See you later': 'Видимо се (Vidimo se)',
      'I need a taxi': 'Треба ми такси (Treba mi taksi)',
      'Is there a pharmacy nearby?':
        'Има ли апотека у близини? (Ima li apoteka u blizini?)',
      'Call a doctor': 'Позовите доктора (Pozovite doktora)',
      'I would like water': 'Желио бих воду (Želio bih vodu)',
      'Is this vegetarian?': 'Да ли је ово вегетаријанско? (Da li je ovo vegetarijansko?)',
    },
  },
  ar: {
    words: {
      I: 'أنا (ana)',
      you: 'أنت (anta)',
      friend: 'صديق (sadiq)',
      family: 'عائلة (a\'ila)',
      name: 'اسم (ism)',
      today: 'اليوم (al-yawm)',
      tomorrow: 'غداً (ghadan)',
      now: 'الآن (al-an)',
      city: 'مدينة (madina)',
      street: 'شارع (shari\')',
      shop: 'متجر (matjar)',
      pharmacy: 'صيدلية (saydaliyya)',
      police: 'شرطة (shurta)',
      ticket: 'تذكرة (tadhkira)',
      coffee: 'قهوة (qahwa)',
      bread: 'خبز (khubz)',
      beer: 'بيرة (bira)',
      left: 'يسار (yasar)',
      right: 'يمين (yamin)',
      near: 'قريب (qarib)',
      cheap: 'رخيص (rakhis)',
      expensive: 'غالي (ghali)',
      open: 'مفتوح (maftuh)',
      closed: 'مغلق (mughlaq)',
      'to want': 'يريد (yurid)',
      'to buy': 'يشتري (yashtari)',
      'to pay': 'يدفع (yadfa\')',
    },
    numbers: {
      '11': 'أحد عشر (ahad ashar)',
      '12': 'اثنا عشر (ithna ashar)',
      '13': 'ثلاثة عشر (thalathat ashar)',
      '14': 'أربعة عشر (arba\'at ashar)',
      '15': 'خمسة عشر (khamsat ashar)',
      '16': 'ستة عشر (sittat ashar)',
      '17': 'سبعة عشر (sab\'at ashar)',
      '18': 'ثمانية عشر (thamaniyat ashar)',
      '19': 'تسعة عشر (tis\'at ashar)',
      '60': 'ستون (sittun)',
      '70': 'سبعون (sab\'un)',
      '80': 'ثمانون (thamanun)',
      '90': 'تسعون (tis\'un)',
      '200': 'مئتان (mi\'atan)',
      '500': 'خمسمائة (khamsumi\'a)',
    },
    sentences: {
      "What's your name?": 'ما اسمك؟ (ma ismuk?)',
      'My name is...': 'اسمي... (ismi...)',
      'Where is the hotel?': 'أين الفندق؟ (ayna al-funduq?)',
      'Where is the airport?': 'أين المطار؟ (ayna al-matar?)',
      'I speak a little': 'أتكلم قليلاً (atakallam qalilan)',
      'Do you have wifi?': 'هل لديكم واي فاي؟ (hal ladaykum wifi?)',
      'I have a reservation': 'لدي حجز (ladayya hajz)',
      "I'm allergic to...": 'لدي حساسية من... (ladayya hasasiyya min...)',
      'How do I get to...?': 'كيف أصل إلى...؟ (kayf asil ila...?)',
      'Can I pay by card?': 'هل يمكنني الدفع بالبطاقة؟ (hal yumkinuni ad-daf\' bil-bitaqa?)',
      'Where can I buy a ticket?':
        'أين يمكنني شراء تذكرة؟ (ayna yumkinuni shira\' tadhkira?)',
      'What time is it?': 'كم الساعة؟ (kam as-sa\'a?)',
      'See you later': 'أراك لاحقاً (araka lahiqan)',
      'I need a taxi': 'أحتاج تاكسي (ahtaju taksi)',
      'Is there a pharmacy nearby?':
        'هل هناك صيدلية قريبة؟ (hal hunaka saydaliyya qariba?)',
      'Call a doctor': 'اتصل بطبيب (ittasil bi-tabib)',
      'I would like water': 'أريد ماء (urid maa\')',
      'Is this vegetarian?': 'هل هذا نباتي؟ (hal hadha nabati?)',
    },
  },
  hi: {
    words: {
      I: 'मैं (main)',
      you: 'तुम (tum)',
      friend: 'दोस्त (dost)',
      family: 'परिवार (parivar)',
      name: 'नाम (naam)',
      today: 'आज (aaj)',
      tomorrow: 'कल (kal)',
      now: 'अब (ab)',
      city: 'शहर (shahar)',
      street: 'सड़क (sadak)',
      shop: 'दुकान (dukaan)',
      pharmacy: 'दवाखाना (davakhana)',
      police: 'पुलिस (pulis)',
      ticket: 'टिकट (ticket)',
      coffee: 'कॉफ़ी (coffee)',
      bread: 'रोटी (roti)',
      beer: 'बीयर (beer)',
      left: 'बायाँ (bayan)',
      right: 'दायाँ (dayan)',
      near: 'पास (paas)',
      cheap: 'सस्ता (sasta)',
      expensive: 'महंगा (mahnga)',
      open: 'खुला (khula)',
      closed: 'बंद (band)',
      'to want': 'चाहना (chahna)',
      'to buy': 'खरीदना (kharidna)',
      'to pay': 'भुगतान करना (bhugtan karna)',
    },
    numbers: {
      '11': 'ग्यारह (gyarah)',
      '12': 'बारह (barah)',
      '13': 'तेरह (terah)',
      '14': 'चौदह (chaudah)',
      '15': 'पंद्रह (pandrah)',
      '16': 'सोलह (solah)',
      '17': 'सत्रह (satrah)',
      '18': 'अठारह (atharah)',
      '19': 'उन्नीस (unnis)',
      '60': 'साठ (saath)',
      '70': 'सत्तर (sattar)',
      '80': 'अस्सी (assi)',
      '90': 'नब्बे (nabbe)',
      '200': 'दो सौ (do sau)',
      '500': 'पाँच सौ (paanch sau)',
    },
    sentences: {
      "What's your name?": 'आपका नाम क्या है? (aapka naam kya hai?)',
      'My name is...': 'मेरा नाम... है (mera naam... hai)',
      'Where is the hotel?': 'होटल कहाँ है? (hotel kahan hai?)',
      'Where is the airport?': 'हवाई अड्डा कहाँ है? (havai adda kahan hai?)',
      'I speak a little': 'मैं थोड़ा बोलता हूँ (main thoda bolta hoon)',
      'Do you have wifi?': 'क्या आपके पास वाईफ़ाई है? (kya aapke paas wifi hai?)',
      'I have a reservation': 'मेरी बुकिंग है (meri booking hai)',
      "I'm allergic to...": 'मुझे... से एलर्जी है (mujhe... se allergy hai)',
      'How do I get to...?': '... कैसे जाऊँ? (... kaise jaun?)',
      'Can I pay by card?': 'क्या मैं कार्ड से भुगतान कर सकता हूँ? (kya main card se bhugtan kar sakta hoon?)',
      'Where can I buy a ticket?':
        'टिकट कहाँ से खरीद सकता हूँ? (ticket kahan se kharid sakta hoon?)',
      'What time is it?': 'क्या समय हुआ है? (kya samay hua hai?)',
      'See you later': 'फिर मिलेंगे (phir milenge)',
      'I need a taxi': 'मुझे टैक्सी चाहिए (mujhe taxi chahiye)',
      'Is there a pharmacy nearby?':
        'क्या पास में दवाखाना है? (kya paas mein davakhana hai?)',
      'Call a doctor': 'डॉक्टर को बुलाएँ (doctor ko bulayen)',
      'I would like water': 'मुझे पानी चाहिए (mujhe paani chahiye)',
      'Is this vegetarian?': 'क्या यह शाकाहारी है? (kya yeh shakahari hai?)',
    },
  },
  da: {
    words: {
      I: 'jeg',
      you: 'du',
      friend: 'ven',
      family: 'familie',
      name: 'navn',
      today: 'i dag',
      tomorrow: 'i morgen',
      now: 'nu',
      city: 'by',
      street: 'gade',
      shop: 'butik',
      pharmacy: 'apotek',
      police: 'politi',
      ticket: 'billet',
      coffee: 'kaffe',
      bread: 'brød',
      beer: 'øl',
      left: 'venstre',
      right: 'højre',
      near: 'nær',
      cheap: 'billig',
      expensive: 'dyr',
      open: 'åben',
      closed: 'lukket',
      'to want': 'at ville',
      'to buy': 'at købe',
      'to pay': 'at betale',
    },
    numbers: {
      '11': 'elleve',
      '12': 'tolv',
      '13': 'tretten',
      '14': 'fjorten',
      '15': 'femten',
      '16': 'seksten',
      '17': 'sytten',
      '18': 'atten',
      '19': 'nitten',
      '60': 'tres',
      '70': 'halvfjerds',
      '80': 'firs',
      '90': 'halvfems',
      '200': 'to hundrede',
      '500': 'fem hundrede',
    },
    sentences: {
      "What's your name?": 'Hvad hedder du?',
      'My name is...': 'Jeg hedder...',
      'Where is the hotel?': 'Hvor er hotellet?',
      'Where is the airport?': 'Hvor er lufthavnen?',
      'I speak a little': 'Jeg taler lidt',
      'Do you have wifi?': 'Har I wifi?',
      'I have a reservation': 'Jeg har en reservation',
      "I'm allergic to...": 'Jeg er allergisk over for...',
      'How do I get to...?': 'Hvordan kommer jeg til...?',
      'Can I pay by card?': 'Kan jeg betale med kort?',
      'Where can I buy a ticket?': 'Hvor kan jeg købe en billet?',
      'What time is it?': 'Hvad er klokken?',
      'See you later': 'Vi ses',
      'I need a taxi': 'Jeg har brug for en taxa',
      'Is there a pharmacy nearby?': 'Er der et apotek i nærheden?',
      'Call a doctor': 'Ring efter en læge',
      'I would like water': 'Jeg vil gerne have vand',
      'Is this vegetarian?': 'Er det vegetarisk?',
    },
  },
  sv: {
    words: {
      I: 'jag',
      you: 'du',
      friend: 'vän',
      family: 'familj',
      name: 'namn',
      today: 'idag',
      tomorrow: 'imorgon',
      now: 'nu',
      city: 'stad',
      street: 'gata',
      shop: 'affär',
      pharmacy: 'apotek',
      police: 'polis',
      ticket: 'biljett',
      coffee: 'kaffe',
      bread: 'bröd',
      beer: 'öl',
      left: 'vänster',
      right: 'höger',
      near: 'nära',
      cheap: 'billig',
      expensive: 'dyr',
      open: 'öppen',
      closed: 'stängd',
      'to want': 'att vilja',
      'to buy': 'att köpa',
      'to pay': 'att betala',
    },
    numbers: {
      '11': 'elva',
      '12': 'tolv',
      '13': 'tretton',
      '14': 'fjorton',
      '15': 'femton',
      '16': 'sexton',
      '17': 'sjutton',
      '18': 'arton',
      '19': 'nitton',
      '60': 'sextio',
      '70': 'sjuttio',
      '80': 'åttio',
      '90': 'nittio',
      '200': 'tvåhundra',
      '500': 'femhundra',
    },
    sentences: {
      "What's your name?": 'Vad heter du?',
      'My name is...': 'Jag heter...',
      'Where is the hotel?': 'Var är hotellet?',
      'Where is the airport?': 'Var är flygplatsen?',
      'I speak a little': 'Jag talar lite',
      'Do you have wifi?': 'Har ni wifi?',
      'I have a reservation': 'Jag har en reservation',
      "I'm allergic to...": 'Jag är allergisk mot...',
      'How do I get to...?': 'Hur tar jag mig till...?',
      'Can I pay by card?': 'Kan jag betala med kort?',
      'Where can I buy a ticket?': 'Var kan jag köpa en biljett?',
      'What time is it?': 'Vad är klockan?',
      'See you later': 'Vi ses',
      'I need a taxi': 'Jag behöver en taxi',
      'Is there a pharmacy nearby?': 'Finns det ett apotek i närheten?',
      'Call a doctor': 'Ring en läkare',
      'I would like water': 'Jag skulle vilja ha vatten',
      'Is this vegetarian?': 'Är det här vegetariskt?',
    },
  },
  nl: {
    words: {
      I: 'ik',
      you: 'jij',
      friend: 'vriend',
      family: 'familie',
      name: 'naam',
      today: 'vandaag',
      tomorrow: 'morgen',
      now: 'nu',
      city: 'stad',
      street: 'straat',
      shop: 'winkel',
      pharmacy: 'apotheek',
      police: 'politie',
      ticket: 'kaartje',
      coffee: 'koffie',
      bread: 'brood',
      beer: 'bier',
      left: 'links',
      right: 'rechts',
      near: 'dichtbij',
      cheap: 'goedkoop',
      expensive: 'duur',
      open: 'open',
      closed: 'gesloten',
      'to want': 'willen',
      'to buy': 'kopen',
      'to pay': 'betalen',
    },
    numbers: {
      '11': 'elf',
      '12': 'twaalf',
      '13': 'dertien',
      '14': 'veertien',
      '15': 'vijftien',
      '16': 'zestien',
      '17': 'zeventien',
      '18': 'achttien',
      '19': 'negentien',
      '60': 'zestig',
      '70': 'zeventig',
      '80': 'tachtig',
      '90': 'negentig',
      '200': 'tweehonderd',
      '500': 'vijfhonderd',
    },
    sentences: {
      "What's your name?": 'Hoe heet je?',
      'My name is...': 'Ik heet...',
      'Where is the hotel?': 'Waar is het hotel?',
      'Where is the airport?': 'Waar is het vliegveld?',
      'I speak a little': 'Ik spreek een beetje',
      'Do you have wifi?': 'Hebben jullie wifi?',
      'I have a reservation': 'Ik heb een reservering',
      "I'm allergic to...": 'Ik ben allergisch voor...',
      'How do I get to...?': 'Hoe kom ik bij...?',
      'Can I pay by card?': 'Kan ik met kaart betalen?',
      'Where can I buy a ticket?': 'Waar kan ik een kaartje kopen?',
      'What time is it?': 'Hoe laat is het?',
      'See you later': 'Tot later',
      'I need a taxi': 'Ik heb een taxi nodig',
      'Is there a pharmacy nearby?': 'Is er een apotheek in de buurt?',
      'Call a doctor': 'Bel een dokter',
      'I would like water': 'Ik wil graag water',
      'Is this vegetarian?': 'Is dit vegetarisch?',
    },
  },
  tr: {
    words: {
      I: 'ben',
      you: 'sen',
      friend: 'arkadaş',
      family: 'aile',
      name: 'ad',
      today: 'bugün',
      tomorrow: 'yarın',
      now: 'şimdi',
      city: 'şehir',
      street: 'sokak',
      shop: 'dükkân',
      pharmacy: 'eczane',
      police: 'polis',
      ticket: 'bilet',
      coffee: 'kahve',
      bread: 'ekmek',
      beer: 'bira',
      left: 'sol',
      right: 'sağ',
      near: 'yakın',
      cheap: 'ucuz',
      expensive: 'pahalı',
      open: 'açık',
      closed: 'kapalı',
      'to want': 'istemek',
      'to buy': 'satın almak',
      'to pay': 'ödemek',
    },
    numbers: {
      '11': 'on bir',
      '12': 'on iki',
      '13': 'on üç',
      '14': 'on dört',
      '15': 'on beş',
      '16': 'on altı',
      '17': 'on yedi',
      '18': 'on sekiz',
      '19': 'on dokuz',
      '60': 'altmış',
      '70': 'yetmiş',
      '80': 'seksen',
      '90': 'doksan',
      '200': 'iki yüz',
      '500': 'beş yüz',
    },
    sentences: {
      "What's your name?": 'Adın ne?',
      'My name is...': 'Adım...',
      'Where is the hotel?': 'Otel nerede?',
      'Where is the airport?': 'Havalimanı nerede?',
      'I speak a little': 'Biraz konuşuyorum',
      'Do you have wifi?': 'Wifi var mı?',
      'I have a reservation': 'Rezervasyonum var',
      "I'm allergic to...": '...alerjim var',
      'How do I get to...?': '...nasıl giderim?',
      'Can I pay by card?': 'Kartla ödeyebilir miyim?',
      'Where can I buy a ticket?': 'Bileti nereden alabilirim?',
      'What time is it?': 'Saat kaç?',
      'See you later': 'Görüşürüz',
      'I need a taxi': 'Taksiye ihtiyacım var',
      'Is there a pharmacy nearby?': 'Yakında eczane var mı?',
      'Call a doctor': 'Doktor çağırın',
      'I would like water': 'Su isterim',
      'Is this vegetarian?': 'Bu vejetaryen mi?',
    },
  },
  ro: {
    words: {
      I: 'eu',
      you: 'tu',
      friend: 'prieten',
      family: 'familie',
      name: 'nume',
      today: 'astăzi',
      tomorrow: 'mâine',
      now: 'acum',
      city: 'oraș',
      street: 'stradă',
      shop: 'magazin',
      pharmacy: 'farmacie',
      police: 'poliție',
      ticket: 'bilet',
      coffee: 'cafea',
      bread: 'pâine',
      beer: 'bere',
      left: 'stânga',
      right: 'dreapta',
      near: 'aproape',
      cheap: 'ieftin',
      expensive: 'scump',
      open: 'deschis',
      closed: 'închis',
      'to want': 'a vrea',
      'to buy': 'a cumpăra',
      'to pay': 'a plăti',
    },
    numbers: {
      '11': 'unsprezece',
      '12': 'doisprezece',
      '13': 'treisprezece',
      '14': 'paisprezece',
      '15': 'cincisprezece',
      '16': 'șaisprezece',
      '17': 'șaptesprezece',
      '18': 'optsprezece',
      '19': 'nouăsprezece',
      '60': 'șaizeci',
      '70': 'șaptezeci',
      '80': 'optzeci',
      '90': 'nouăzeci',
      '200': 'două sute',
      '500': 'cinci sute',
    },
    sentences: {
      "What's your name?": 'Cum te cheamă?',
      'My name is...': 'Mă numesc...',
      'Where is the hotel?': 'Unde este hotelul?',
      'Where is the airport?': 'Unde este aeroportul?',
      'I speak a little': 'Vorbesc puțin',
      'Do you have wifi?': 'Aveți wifi?',
      'I have a reservation': 'Am o rezervare',
      "I'm allergic to...": 'Sunt alergic la...',
      'How do I get to...?': 'Cum ajung la...?',
      'Can I pay by card?': 'Pot plăti cu cardul?',
      'Where can I buy a ticket?': 'Unde pot cumpăra un bilet?',
      'What time is it?': 'Cât este ceasul?',
      'See you later': 'Ne vedem mai târziu',
      'I need a taxi': 'Am nevoie de un taxi',
      'Is there a pharmacy nearby?': 'Este o farmacie în apropiere?',
      'Call a doctor': 'Chemați un doctor',
      'I would like water': 'Aș dori apă',
      'Is this vegetarian?': 'Este vegetarian?',
    },
  },
  is: {
    words: {
      I: 'ég',
      you: 'þú',
      friend: 'vinur',
      family: 'fjölskylda',
      name: 'nafn',
      today: 'í dag',
      tomorrow: 'á morgun',
      now: 'núna',
      city: 'borg',
      street: 'gata',
      shop: 'búð',
      pharmacy: 'apótek',
      police: 'lögregla',
      ticket: 'miði',
      coffee: 'kaffi',
      bread: 'brauð',
      beer: 'bjór',
      left: 'vinstri',
      right: 'hægri',
      near: 'nálægt',
      cheap: 'ódýrt',
      expensive: 'dýrt',
      open: 'opið',
      closed: 'lokað',
      'to want': 'að vilja',
      'to buy': 'að kaupa',
      'to pay': 'að borga',
    },
    numbers: {
      '11': 'ellefu',
      '12': 'tólf',
      '13': 'þrettán',
      '14': 'fjórtán',
      '15': 'fimmtán',
      '16': 'sextán',
      '17': 'sautján',
      '18': 'átján',
      '19': 'nítján',
      '60': 'sextíu',
      '70': 'sjötíu',
      '80': 'áttatíu',
      '90': 'níutíu',
      '200': 'tvö hundruð',
      '500': 'fimm hundruð',
    },
    sentences: {
      "What's your name?": 'Hvað heitir þú?',
      'My name is...': 'Ég heiti...',
      'Where is the hotel?': 'Hvar er hótelið?',
      'Where is the airport?': 'Hvar er flugvöllurinn?',
      'I speak a little': 'Ég tala smá',
      'Do you have wifi?': 'Eigið þið wifi?',
      'I have a reservation': 'Ég er með bókun',
      "I'm allergic to...": 'Ég er með ofnæmi fyrir...',
      'How do I get to...?': 'Hvernig kemst ég til...?',
      'Can I pay by card?': 'Get ég borgað með korti?',
      'Where can I buy a ticket?': 'Hvar get ég keypt miða?',
      'What time is it?': 'Hvað er klukkan?',
      'See you later': 'Sjáumst síðar',
      'I need a taxi': 'Ég þarf leigubíl',
      'Is there a pharmacy nearby?': 'Er apótek hér nálægt?',
      'Call a doctor': 'Hringdu í lækni',
      'I would like water': 'Ég ætla að fá vatn',
      'Is this vegetarian?': 'Er þetta jurtafæði?',
    },
  },
  pt: {
    words: {
      I: 'eu',
      you: 'você',
      friend: 'amigo',
      family: 'família',
      name: 'nome',
      today: 'hoje',
      tomorrow: 'amanhã',
      now: 'agora',
      city: 'cidade',
      street: 'rua',
      shop: 'loja',
      pharmacy: 'farmácia',
      police: 'polícia',
      ticket: 'bilhete',
      coffee: 'café',
      bread: 'pão',
      beer: 'cerveja',
      left: 'esquerda',
      right: 'direita',
      near: 'perto',
      cheap: 'barato',
      expensive: 'caro',
      open: 'aberto',
      closed: 'fechado',
      'to want': 'querer',
      'to buy': 'comprar',
      'to pay': 'pagar',
    },
    numbers: {
      '11': 'onze',
      '12': 'doze',
      '13': 'treze',
      '14': 'catorze',
      '15': 'quinze',
      '16': 'dezasseis',
      '17': 'dezassete',
      '18': 'dezoito',
      '19': 'dezanove',
      '60': 'sessenta',
      '70': 'setenta',
      '80': 'oitenta',
      '90': 'noventa',
      '200': 'duzentos',
      '500': 'quinhentos',
    },
    sentences: {
      "What's your name?": 'Como se chama?',
      'My name is...': 'O meu nome é...',
      'Where is the hotel?': 'Onde fica o hotel?',
      'Where is the airport?': 'Onde fica o aeroporto?',
      'I speak a little': 'Falo um pouco',
      'Do you have wifi?': 'Têm wifi?',
      'I have a reservation': 'Tenho uma reserva',
      "I'm allergic to...": 'Sou alérgico a...',
      'How do I get to...?': 'Como chego a...?',
      'Can I pay by card?': 'Posso pagar com cartão?',
      'Where can I buy a ticket?': 'Onde posso comprar um bilhete?',
      'What time is it?': 'Que horas são?',
      'See you later': 'Até logo',
      'I need a taxi': 'Preciso de um táxi',
      'Is there a pharmacy nearby?': 'Há uma farmácia perto?',
      'Call a doctor': 'Chame um médico',
      'I would like water': 'Queria água',
      'Is this vegetarian?': 'Isto é vegetariano?',
    },
  },
  cy: {
    words: {
      I: 'fi',
      you: 'ti',
      friend: 'ffrind',
      family: 'teulu',
      name: 'enw',
      today: 'heddiw',
      tomorrow: 'yfory',
      now: 'nawr',
      city: 'dinas',
      street: 'stryd',
      shop: 'siop',
      pharmacy: 'fferyllfa',
      police: 'heddlu',
      ticket: 'tocyn',
      coffee: 'coffi',
      bread: 'bara',
      beer: 'cwrw',
      left: 'chwith',
      right: 'de',
      near: 'agos',
      cheap: 'rhad',
      expensive: 'drud',
      open: 'ar agor',
      closed: 'ar gau',
      'to want': 'eisiau',
      'to buy': 'prynu',
      'to pay': 'talu',
    },
    numbers: {
      '11': 'un ar ddeg',
      '12': 'deuddeg',
      '13': 'tri ar ddeg',
      '14': 'pedwar ar ddeg',
      '15': 'pymtheg',
      '16': 'un ar bymtheg',
      '17': 'dau ar bymtheg',
      '18': 'deunaw',
      '19': 'pedwar ar bymtheg',
      '60': 'trigain',
      '70': 'deg a thrigain',
      '80': 'pedwar ugain',
      '90': 'deg a phedwar ugain',
      '200': 'dau gant',
      '500': 'pum cant',
    },
    sentences: {
      "What's your name?": 'Beth yw dy enw?',
      'My name is...': 'Fy enw i yw...',
      'Where is the hotel?': 'Ble mae\'r gwesty?',
      'Where is the airport?': 'Ble mae\'r maes awyr?',
      'I speak a little': 'Dwi\'n siarad ychydig',
      'Do you have wifi?': 'Oes wifi gyda chi?',
      'I have a reservation': 'Mae gen i gadw',
      "I'm allergic to...": 'Dwi\'n alergaidd i...',
      'How do I get to...?': 'Sut alla i gyrraedd...?',
      'Can I pay by card?': 'Alla i dalu â cherdyn?',
      'Where can I buy a ticket?': 'Ble alla i brynu tocyn?',
      'What time is it?': 'Faint o\'r gloch ydy hi?',
      'See you later': 'Wela i di wedyn',
      'I need a taxi': 'Dwi angen tacsi',
      'Is there a pharmacy nearby?': 'Oes fferyllfa gerllaw?',
      'Call a doctor': 'Ffoniwch feddyg',
      'I would like water': 'Hoffwn i ddŵr',
      'Is this vegetarian?': 'Ydy hwn yn llysieuol?',
    },
  },
  he: {
    words: {
      I: 'אני',
      you: 'אתה',
      friend: 'חבר',
      family: 'משפחה',
      name: 'שם',
      today: 'היום',
      tomorrow: 'מחר',
      now: 'עכשיו',
      city: 'עיר',
      street: 'רחוב',
      shop: 'חנות',
      pharmacy: 'בית מרקחת',
      police: 'משטרה',
      ticket: 'כרטיס',
      coffee: 'קפה',
      bread: 'לחם',
      beer: 'בירה',
      left: 'שמאל',
      right: 'ימין',
      near: 'קרוב',
      cheap: 'זול',
      expensive: 'יקר',
      open: 'פתוח',
      closed: 'סגור',
      'to want': 'לרצות',
      'to buy': 'לקנות',
      'to pay': 'לשלם',
    },
    numbers: {
      '11': 'אחת עשרה',
      '12': 'שתים עשרה',
      '13': 'שלוש עשרה',
      '14': 'ארבע עשרה',
      '15': 'חמש עשרה',
      '16': 'שש עשרה',
      '17': 'שבע עשרה',
      '18': 'שמונה עשרה',
      '19': 'תשע עשרה',
      '60': 'שישים',
      '70': 'שבעים',
      '80': 'שמונים',
      '90': 'תשעים',
      '200': 'מאתיים',
      '500': 'חמש מאות',
    },
    sentences: {
      "What's your name?": 'איך קוראים לך?',
      'My name is...': 'קוראים לי...',
      'Where is the hotel?': 'איפה המלון?',
      'Where is the airport?': 'איפה שדה התעופה?',
      'I speak a little': 'אני מדבר קצת',
      'Do you have wifi?': 'יש לכם וויי-פיי?',
      'I have a reservation': 'יש לי הזמנה',
      "I'm allergic to...": 'אני אלרגי ל...',
      'How do I get to...?': 'איך מגיעים ל...?',
      'Can I pay by card?': 'אפשר לשלם בכרטיס?',
      'Where can I buy a ticket?': 'איפה אפשר לקנות כרטיס?',
      'What time is it?': 'מה השעה?',
      'See you later': 'נתראה אחר כך',
      'I need a taxi': 'אני צריך מונית',
      'Is there a pharmacy nearby?': 'יש בית מרקחת בקרבת מקום?',
      'Call a doctor': 'תתקשרו לרופא',
      'I would like water': 'אני רוצה מים',
      'Is this vegetarian?': 'זה צמחוני?',
    },
  },
  fa: {
    words: {
      I: 'من',
      you: 'تو',
      friend: 'دوست',
      family: 'خانواده',
      name: 'اسم',
      today: 'امروز',
      tomorrow: 'فردا',
      now: 'الان',
      city: 'شهر',
      street: 'خیابان',
      shop: 'فروشگاه',
      pharmacy: 'داروخانه',
      police: 'پلیس',
      ticket: 'بلیط',
      coffee: 'قهوه',
      bread: 'نان',
      beer: 'آبجو',
      left: 'چپ',
      right: 'راست',
      near: 'نزدیک',
      cheap: 'ارزان',
      expensive: 'گران',
      open: 'باز',
      closed: 'بسته',
      'to want': 'خواستن',
      'to buy': 'خریدن',
      'to pay': 'پرداخت کردن',
    },
    numbers: {
      '11': 'یازده',
      '12': 'دوازده',
      '13': 'سیزده',
      '14': 'چهارده',
      '15': 'پانزده',
      '16': 'شانزده',
      '17': 'هفده',
      '18': 'هجده',
      '19': 'نوزده',
      '60': 'شصت',
      '70': 'هفتاد',
      '80': 'هشتاد',
      '90': 'نود',
      '200': 'دویست',
      '500': 'پانصد',
    },
    sentences: {
      "What's your name?": 'اسم شما چیست؟',
      'My name is...': 'اسم من... است',
      'Where is the hotel?': 'هتل کجاست؟',
      'Where is the airport?': 'فرودگاه کجاست؟',
      'I speak a little': 'کمی حرف می‌زنم',
      'Do you have wifi?': 'وای‌فای دارید؟',
      'I have a reservation': 'رزرو دارم',
      "I'm allergic to...": 'به... حساسیت دارم',
      'How do I get to...?': 'چطور به... بروم؟',
      'Can I pay by card?': 'می‌توانم با کارت پرداخت کنم؟',
      'Where can I buy a ticket?': 'از کجا می‌توانم بلیط بخرم؟',
      'What time is it?': 'ساعت چند است؟',
      'See you later': 'بعداً می‌بینمت',
      'I need a taxi': 'به تاکسی نیاز دارم',
      'Is there a pharmacy nearby?': 'داروخانه‌ای نزدیک هست؟',
      'Call a doctor': 'با پزشک تماس بگیرید',
      'I would like water': 'آب می‌خواهم',
      'Is this vegetarian?': 'این گیاهی است؟',
    },
  },
  af: {
    words: {
      I: 'ek',
      you: 'jy',
      friend: 'vriend',
      family: 'familie',
      name: 'naam',
      today: 'vandag',
      tomorrow: 'môre',
      now: 'nou',
      city: 'stad',
      street: 'straat',
      shop: 'winkel',
      pharmacy: 'apteek',
      police: 'polisie',
      ticket: 'kaartjie',
      coffee: 'koffie',
      bread: 'brood',
      beer: 'bier',
      left: 'links',
      right: 'regs',
      near: 'naby',
      cheap: 'goedkoop',
      expensive: 'duur',
      open: 'oop',
      closed: 'toe',
      'to want': 'wil hê',
      'to buy': 'koop',
      'to pay': 'betaal',
    },
    numbers: {
      '11': 'elf',
      '12': 'twaalf',
      '13': 'dertien',
      '14': 'veertien',
      '15': 'vyftien',
      '16': 'sestien',
      '17': 'sewentien',
      '18': 'agtien',
      '19': 'negentien',
      '60': 'sestig',
      '70': 'sewentig',
      '80': 'tagtig',
      '90': 'negentig',
      '200': 'tweehonderd',
      '500': 'vyfhonderd',
    },
    sentences: {
      "What's your name?": 'Wat is jou naam?',
      'My name is...': 'My naam is...',
      'Where is the hotel?': 'Waar is die hotel?',
      'Where is the airport?': 'Waar is die lughawe?',
      'I speak a little': 'Ek praat \'n bietjie',
      'Do you have wifi?': 'Het julle wifi?',
      'I have a reservation': 'Ek het \'n bespreking',
      "I'm allergic to...": 'Ek is allergies vir...',
      'How do I get to...?': 'Hoe kom ek by...?',
      'Can I pay by card?': 'Kan ek met kaart betaal?',
      'Where can I buy a ticket?': 'Waar kan ek \'n kaartjie koop?',
      'What time is it?': 'Hoe laat is dit?',
      'See you later': 'Sien jou later',
      'I need a taxi': 'Ek het \'n taxi nodig',
      'Is there a pharmacy nearby?': 'Is daar \'n apteek naby?',
      'Call a doctor': 'Bel \'n dokter',
      'I would like water': 'Ek wil graag water hê',
      'Is this vegetarian?': 'Is dit vegetaries?',
    },
  },
  sr: {
    words: {
      I: 'ја (ja)',
      you: 'ти (ti)',
      friend: 'пријатељ (prijatelj)',
      family: 'породица (porodica)',
      name: 'име (ime)',
      today: 'данас (danas)',
      tomorrow: 'сутра (sutra)',
      now: 'сада (sada)',
      city: 'град (grad)',
      street: 'улица (ulica)',
      shop: 'продавница (prodavnica)',
      pharmacy: 'апотека (apoteka)',
      police: 'полиција (policija)',
      ticket: 'карта (karta)',
      coffee: 'кафа (kafa)',
      bread: 'хлеб (hleb)',
      beer: 'пиво (pivo)',
      left: 'лево (levo)',
      right: 'десно (desno)',
      near: 'близу (blizu)',
      cheap: 'јефтино (jeftino)',
      expensive: 'скупо (skupo)',
      open: 'отворено (otvoreno)',
      closed: 'затворено (zatvoreno)',
      'to want': 'хтети (hteti)',
      'to buy': 'купити (kupiti)',
      'to pay': 'платити (platiti)',
    },
    numbers: {
      '11': 'једанаест (jedanaest)',
      '12': 'дванаест (dvanaest)',
      '13': 'тринаест (trinaest)',
      '14': 'четрнаест (četrnaest)',
      '15': 'петнаест (petnaest)',
      '16': 'шеснаест (šesnaest)',
      '17': 'седамнаест (sedamnaest)',
      '18': 'осамнаест (osamnaest)',
      '19': 'деветнаест (devetnaest)',
      '60': 'шездесет (šezdeset)',
      '70': 'седамдесет (sedamdeset)',
      '80': 'осамдесет (osamdeset)',
      '90': 'деведесет (devedeset)',
      '200': 'двеста (dvesta)',
      '500': 'петсто (petsto)',
    },
    sentences: {
      "What's your name?": 'Како се зовеш? (Kako se zoveš?)',
      'My name is...': 'Зовем се... (Zovem se...)',
      'Where is the hotel?': 'Где је хотел? (Gde je hotel?)',
      'Where is the airport?': 'Где је аеродром? (Gde je aerodrom?)',
      'I speak a little': 'Говорим мало (Govorim malo)',
      'Do you have wifi?': 'Имате ли wifi? (Imate li wifi?)',
      'I have a reservation': 'Имам резервацију (Imam rezervaciju)',
      "I'm allergic to...": 'Алергичан сам на... (Alergičan sam na...)',
      'How do I get to...?': 'Како да дођем до...? (Kako da dođem do...?)',
      'Can I pay by card?': 'Могу ли да платим картицом? (Mogu li da platim karticom?)',
      'Where can I buy a ticket?':
        'Где могу да купим карту? (Gde mogu da kupim kartu?)',
      'What time is it?': 'Колико је сати? (Koliko je sati?)',
      'See you later': 'Видимо се (Vidimo se)',
      'I need a taxi': 'Треба ми такси (Treba mi taksi)',
      'Is there a pharmacy nearby?':
        'Има ли апотека у близини? (Ima li apoteka u blizini?)',
      'Call a doctor': 'Позовите доктора (Pozovite doktora)',
      'I would like water': 'Желео бих воду (Želeo bih vodu)',
      'Is this vegetarian?': 'Да ли је ово вегетаријанско? (Da li je ovo vegetarijansko?)',
    },
  },
  bs: {
    words: {
      I: 'ja',
      you: 'ti',
      friend: 'prijatelj',
      family: 'porodica',
      name: 'ime',
      today: 'danas',
      tomorrow: 'sutra',
      now: 'sada',
      city: 'grad',
      street: 'ulica',
      shop: 'prodavnica',
      pharmacy: 'apoteka',
      police: 'policija',
      ticket: 'karta',
      coffee: 'kafa',
      bread: 'hljeb',
      beer: 'pivo',
      left: 'lijevo',
      right: 'desno',
      near: 'blizu',
      cheap: 'jeftino',
      expensive: 'skupo',
      open: 'otvoreno',
      closed: 'zatvoreno',
      'to want': 'htjeti',
      'to buy': 'kupiti',
      'to pay': 'platiti',
    },
    numbers: {
      '11': 'jedanaest',
      '12': 'dvanaest',
      '13': 'trinaest',
      '14': 'četrnaest',
      '15': 'petnaest',
      '16': 'šesnaest',
      '17': 'sedamnaest',
      '18': 'osamnaest',
      '19': 'devetnaest',
      '60': 'šezdeset',
      '70': 'sedamdeset',
      '80': 'osamdeset',
      '90': 'devedeset',
      '200': 'dvjesta',
      '500': 'petsto',
    },
    sentences: {
      "What's your name?": 'Kako se zoveš?',
      'My name is...': 'Zovem se...',
      'Where is the hotel?': 'Gdje je hotel?',
      'Where is the airport?': 'Gdje je aerodrom?',
      'I speak a little': 'Govorim malo',
      'Do you have wifi?': 'Imate li wifi?',
      'I have a reservation': 'Imam rezervaciju',
      "I'm allergic to...": 'Alergičan sam na...',
      'How do I get to...?': 'Kako da dođem do...?',
      'Can I pay by card?': 'Mogu li platiti karticom?',
      'Where can I buy a ticket?': 'Gdje mogu kupiti kartu?',
      'What time is it?': 'Koliko je sati?',
      'See you later': 'Vidimo se',
      'I need a taxi': 'Treba mi taksi',
      'Is there a pharmacy nearby?': 'Ima li apoteka u blizini?',
      'Call a doctor': 'Pozovite doktora',
      'I would like water': 'Želio bih vodu',
      'Is this vegetarian?': 'Je li ovo vegetarijansko?',
    },
  },
  el: {
    words: {
      I: 'εγώ',
      you: 'εσύ',
      friend: 'φίλος',
      family: 'οικογένεια',
      name: 'όνομα',
      today: 'σήμερα',
      tomorrow: 'αύριο',
      now: 'τώρα',
      city: 'πόλη',
      street: 'δρόμος',
      shop: 'κατάστημα',
      pharmacy: 'φαρμακείο',
      police: 'αστυνομία',
      ticket: 'εισιτήριο',
      coffee: 'καφές',
      bread: 'ψωμί',
      beer: 'μπίρα',
      left: 'αριστερά',
      right: 'δεξιά',
      near: 'κοντά',
      cheap: 'φθηνό',
      expensive: 'ακριβό',
      open: 'ανοιχτό',
      closed: 'κλειστό',
      'to want': 'θέλω',
      'to buy': 'αγοράζω',
      'to pay': 'πληρώνω',
    },
    numbers: {
      '11': 'έντεκα',
      '12': 'δώδεκα',
      '13': 'δεκατρία',
      '14': 'δεκατέσσερα',
      '15': 'δεκαπέντε',
      '16': 'δεκαέξι',
      '17': 'δεκαεπτά',
      '18': 'δεκαοκτώ',
      '19': 'δεκαεννέα',
      '60': 'εξήντα',
      '70': 'εβδομήντα',
      '80': 'ογδόντα',
      '90': 'ενενήντα',
      '200': 'διακόσια',
      '500': 'πεντακόσια',
    },
    sentences: {
      "What's your name?": 'Πώς σε λένε;',
      'My name is...': 'Με λένε...',
      'Where is the hotel?': 'Πού είναι το ξενοδοχείο;',
      'Where is the airport?': 'Πού είναι το αεροδρόμιο;',
      'I speak a little': 'Μιλάω λίγο',
      'Do you have wifi?': 'Έχετε wifi;',
      'I have a reservation': 'Έχω κράτηση',
      "I'm allergic to...": 'Έχω αλλεργία σε...',
      'How do I get to...?': 'Πώς πάω στο...;',
      'Can I pay by card?': 'Μπορώ να πληρώσω με κάρτα;',
      'Where can I buy a ticket?': 'Πού μπορώ να αγοράσω εισιτήριο;',
      'What time is it?': 'Τι ώρα είναι;',
      'See you later': 'Τα λέμε αργότερα',
      'I need a taxi': 'Χρειάζομαι ταξί',
      'Is there a pharmacy nearby?': 'Υπάρχει φαρμακείο κοντά;',
      'Call a doctor': 'Καλέστε γιατρό',
      'I would like water': 'Θα ήθελα νερό',
      'Is this vegetarian?': 'Είναι χορτοφαγικό;',
    },
  },
  am: {
    words: {
      'I': 'እኔ (ine)',
      'you': 'አንተ (ante)',
      'friend': 'ጉደኛ (guadegna)',
      'family': 'ቤተሰብ (beteseb)',
      'name': 'ስም (sim)',
      'today': 'ዛሬ (zare)',
      'tomorrow': 'ነገ (nege)',
      'now': 'አሁን (ahun)',
      'city': 'ከተማ (ketema)',
      'street': 'መንገድ (menged)',
      'shop': 'ሱቅ (suq)',
      'pharmacy': 'መድዃኒት ቤት (medhanit bet)',
      'police': 'ፖሊስ (polis)',
      'ticket': 'ትዬት (ticket)',
      'coffee': 'ቡና (buna)',
      'bread': 'ዳቦ (dabo)',
      'beer': 'ቢራ (bira)',
      'left': 'ግራ (gira)',
      'right': 'ቀኝ (kegn)',
      'near': 'ቅርብ (kirb)',
      'cheap': 'ርካሽ (rikash)',
      'expensive': 'ውድ (wid)',
      'open': 'ክፍት (kift)',
      'closed': 'ዝግ (zig)',
      'to want': 'መፈለግ (mefelleg)',
      'to buy': 'መግዛት (megizat)',
      'to pay': 'መክፈል (mekfel)',
    },
    numbers: {
      '11': 'አስራ አንድ (asra and)',
      '12': 'አስራ ሁለት (asra hulet)',
      '13': 'አስራ ሶስት (asra sost)',
      '14': 'አስራ አራት (asra arat)',
      '15': 'አስራ አምስት (asra amist)',
      '16': 'አስራ ስድስት (asra sidist)',
      '17': 'አስራ ሰባት (asra sebat)',
      '18': 'አስራ ስምንት (asra simint)',
      '19': 'አስራ ዘጨኝ (asra zetegn)',
      '60': 'ስልሳ (silsa)',
      '70': 'ሰባ (seba)',
      '80': 'ሰማንያ (semanya)',
      '90': 'ዘጨና (zetena)',
      '200': 'ሁለት መቶ (hulet meto)',
      '500': 'አምስት መቶ (amist meto)',
    },
    sentences: {
      'What\'s your name?': 'ስምህ ማን ነው? (simih man new?)',
      'My name is...': 'ስሜ... ነው (sime... new)',
      'Where is the hotel?': 'ሆቴሉ የት ነው? (hotelu yet new?)',
      'Where is the airport?': 'አየር ማረፊያው የት ነው? (ayer marefiaw yet new?)',
      'I speak a little': 'ትንሽ እናገራለሁ (tinish inageralehu)',
      'Do you have wifi?': 'ዋይፋይ አለ? (wifi alle?)',
      'I have a reservation': 'ቀጠሮ አለኝ (qetero allegn)',
      'I\'m allergic to...': 'ለ... አለርጂ አለኝ (le... allergy allegn)',
      'How do I get to...?': 'ወደ... እንዴት እደርሳለሁ? (wede... indet idersalehu?)',
      'Can I pay by card?': 'በካርድ መክፈል እችላለሁ? (be card mekfel ichilalehu?)',
      'Where can I buy a ticket?': 'ትዬት የት መግዛት እችላለሁ? (ticket yet megizat ichilalehu?)',
      'What time is it?': 'ስንት ሰዓት ነው? (sint seat new?)',
      'See you later': 'ዋላ እንገናኝ (hwala ingenagn)',
      'I need a taxi': 'ታክሲ እፈልጋለሁ (taksi ifeligalehu)',
      'Is there a pharmacy nearby?': 'በአቅራቢያ መድዃኒት ቤት አለ? (beaqrabiya medhanit bet alle?)',
      'Call a doctor': 'ሐኪም ይደውሉ (hakim yidewlu)',
      'I would like water': 'ውሃ እፈልጋለሁ (wuha ifeligalehu)',
      'Is this vegetarian?': 'ይህ የአትክልት ነው? (yih ye atkilt new?)',
    },
  },
  bg: {
    words: {
      I: 'аз (az)',
      you: 'ти (ti)',
      friend: 'приятел (priyatel)',
      family: 'семейство (semeystvo)',
      name: 'име (ime)',
      today: 'днес (dnes)',
      tomorrow: 'утре (utre)',
      now: 'сега (sega)',
      city: 'град (grad)',
      street: 'улица (ulitsa)',
      shop: 'магазин (magazin)',
      pharmacy: 'аптека (apteka)',
      police: 'полиция (politsiya)',
      ticket: 'билет (bilet)',
      coffee: 'кафе (kafe)',
      bread: 'хляб (hlyab)',
      beer: 'бира (bira)',
      left: 'ляво (lyavo)',
      right: 'дясно (dyasno)',
      near: 'близо (blizo)',
      cheap: 'евтин (evtin)',
      expensive: 'скъп (skap)',
      open: 'отворено (otvoreno)',
      closed: 'затворено (zatvoreno)',
      'to want': 'искам (iskam)',
      'to buy': 'купувам (kupuvam)',
      'to pay': 'плащам (plashtam)',
    },
    numbers: {
      '11': 'единадесет (edinadeset)',
      '12': 'дванадесет (dvanadeset)',
      '13': 'тринадесет (trinadeset)',
      '14': 'четиринадесет (chetirinadeset)',
      '15': 'петнадесет (petnadeset)',
      '16': 'шестнадесет (shesnadeset)',
      '17': 'седемнадесет (sedemnadeset)',
      '18': 'осемнадесет (osemnadeset)',
      '19': 'деветнадесет (devetnadeset)',
      '60': 'шестдесет (shestdeset)',
      '70': 'седемдесет (sedemdeset)',
      '80': 'осемдесет (osemdeset)',
      '90': 'деветдесет (devetdeset)',
      '200': 'двеста (dvesta)',
      '500': 'петстотин (petstotin)',
    },
    sentences: {
      "What's your name?": 'Как се казваш? (Kak se kazvash?)',
      'My name is...': 'Казвам се... (Kazvam se...)',
      'Where is the hotel?': 'Къде е хотелът? (Kade e hotelat?)',
      'Where is the airport?': 'Къде е летището? (Kade e letishteto?)',
      'I speak a little': 'Говоря малко (Govorya malko)',
      'Do you have wifi?': 'Имате ли wifi? (Imate li wifi?)',
      'I have a reservation': 'Имам резервация (Imam rezervatsiya)',
      "I'm allergic to...": 'Алергичен съм към... (Alergichen sam kam...)',
      'How do I get to...?': 'Как да стигна до...? (Kak da stigma do...?)',
      'Can I pay by card?': 'Мога ли да платя с карта? (Moga li da platya s karta?)',
      'Where can I buy a ticket?':
        'Къде мога да купя билет? (Kade moga da kupya bilet?)',
      'What time is it?': 'Колко е часът? (Kolko e chasat?)',
      'See you later': 'До скоро (Do skoro)',
      'I need a taxi': 'Нуждая се от такси (Nuzhdaya se ot taksi)',
      'Is there a pharmacy nearby?':
        'Има ли аптека наблизо? (Ima li apteka nablizo?)',
      'Call a doctor': 'Повикайте лекар (Povikayte lekar)',
      'I would like water': 'Искам вода (Iskam voda)',
      'Is this vegetarian?': 'Това вегетарианско ли е? (Tova vegetariansko li e?)',
    },
  },
  cs: {
    words: {
      I: 'já',
      you: 'ty',
      friend: 'přítel',
      family: 'rodina',
      name: 'jméno',
      today: 'dnes',
      tomorrow: 'zítra',
      now: 'teď',
      city: 'město',
      street: 'ulice',
      shop: 'obchod',
      pharmacy: 'lékárna',
      police: 'policie',
      ticket: 'jízdenka',
      coffee: 'káva',
      bread: 'chléb',
      beer: 'pivo',
      left: 'vlevo',
      right: 'vpravo',
      near: 'blízko',
      cheap: 'levný',
      expensive: 'drahý',
      open: 'otevřeno',
      closed: 'zavřeno',
      'to want': 'chtít',
      'to buy': 'koupit',
      'to pay': 'platit',
    },
    numbers: {
      '11': 'jedenáct',
      '12': 'dvanáct',
      '13': 'třináct',
      '14': 'čtrnáct',
      '15': 'patnáct',
      '16': 'šestnáct',
      '17': 'sedmnáct',
      '18': 'osmnáct',
      '19': 'devatenáct',
      '60': 'šedesát',
      '70': 'sedmdesát',
      '80': 'osmdesát',
      '90': 'devadesát',
      '200': 'dvě stě',
      '500': 'pět set',
    },
    sentences: {
      "What's your name?": 'Jak se jmenuješ?',
      'My name is...': 'Jmenuji se...',
      'Where is the hotel?': 'Kde je hotel?',
      'Where is the airport?': 'Kde je letiště?',
      'I speak a little': 'Mluvím trochu',
      'Do you have wifi?': 'Máte wifi?',
      'I have a reservation': 'Mám rezervaci',
      "I'm allergic to...": 'Jsem alergický na...',
      'How do I get to...?': 'Jak se dostanu k...?',
      'Can I pay by card?': 'Mohu platit kartou?',
      'Where can I buy a ticket?': 'Kde si můžu koupit jízdenku?',
      'What time is it?': 'Kolik je hodin?',
      'See you later': 'Uvidíme se později',
      'I need a taxi': 'Potřebuji taxi',
      'Is there a pharmacy nearby?': 'Je tu poblíž lékárna?',
      'Call a doctor': 'Zavolejte lékaře',
      'I would like water': 'Chtěl bych vodu',
      'Is this vegetarian?': 'Je to vegetariánské?',
    },
  },
  fi: {
    words: {
      I: 'minä',
      you: 'sinä',
      friend: 'ystävä',
      family: 'perhe',
      name: 'nimi',
      today: 'tänään',
      tomorrow: 'huomenna',
      now: 'nyt',
      city: 'kaupunki',
      street: 'katu',
      shop: 'kauppa',
      pharmacy: 'apteekki',
      police: 'poliisi',
      ticket: 'lippu',
      coffee: 'kahvi',
      bread: 'leipä',
      beer: 'olut',
      left: 'vasen',
      right: 'oikea',
      near: 'lähellä',
      cheap: 'halpa',
      expensive: 'kallis',
      open: 'auki',
      closed: 'kiinni',
      'to want': 'haluta',
      'to buy': 'ostaa',
      'to pay': 'maksaa',
    },
    numbers: {
      '11': 'yksitoista',
      '12': 'kaksitoista',
      '13': 'kolmetoista',
      '14': 'neljätoista',
      '15': 'viisitoista',
      '16': 'kuusitoista',
      '17': 'seitsemäntoista',
      '18': 'kahdeksantoista',
      '19': 'yhdeksäntoista',
      '60': 'kuusikymmentä',
      '70': 'seitsemänkymmentä',
      '80': 'kahdeksankymmentä',
      '90': 'yhdeksänkymmentä',
      '200': 'kaksisataa',
      '500': 'viisisataa',
    },
    sentences: {
      "What's your name?": 'Mikä sinun nimesi on?',
      'My name is...': 'Minun nimeni on...',
      'Where is the hotel?': 'Missä hotelli on?',
      'Where is the airport?': 'Missä lentokenttä on?',
      'I speak a little': 'Puhun vähän',
      'Do you have wifi?': 'Onko teillä wifi?',
      'I have a reservation': 'Minulla on varaus',
      "I'm allergic to...": 'Olen allerginen...',
      'How do I get to...?': 'Miten pääsen...?',
      'Can I pay by card?': 'Voinko maksaa kortilla?',
      'Where can I buy a ticket?': 'Mistä voin ostaa lipun?',
      'What time is it?': 'Mitä kello on?',
      'See you later': 'Nähdään myöhemmin',
      'I need a taxi': 'Tarvitsen taksin',
      'Is there a pharmacy nearby?': 'Onko lähellä apteekkia?',
      'Call a doctor': 'Soita lääkärille',
      'I would like water': 'Haluaisin vettä',
      'Is this vegetarian?': 'Onko tämä kasvisruokaa?',
    },
  },
  hu: {
    words: {
      I: 'én',
      you: 'te',
      friend: 'barát',
      family: 'család',
      name: 'név',
      today: 'ma',
      tomorrow: 'holnap',
      now: 'most',
      city: 'város',
      street: 'utca',
      shop: 'bolt',
      pharmacy: 'gyógyszertár',
      police: 'rendőrség',
      ticket: 'jegy',
      coffee: 'kávé',
      bread: 'kenyér',
      beer: 'sör',
      left: 'bal',
      right: 'jobb',
      near: 'közel',
      cheap: 'olcsó',
      expensive: 'drága',
      open: 'nyitva',
      closed: 'zárva',
      'to want': 'akarni',
      'to buy': 'venni',
      'to pay': 'fizetni',
    },
    numbers: {
      '11': 'tizenegy',
      '12': 'tizenkettő',
      '13': 'tizenhárom',
      '14': 'tizennégy',
      '15': 'tizenöt',
      '16': 'tizenhat',
      '17': 'tizenhét',
      '18': 'tizennyolc',
      '19': 'tizenkilenc',
      '60': 'hatvan',
      '70': 'hetven',
      '80': 'nyolcvan',
      '90': 'kilencven',
      '200': 'kétszáz',
      '500': 'ötszáz',
    },
    sentences: {
      "What's your name?": 'Mi a neved?',
      'My name is...': 'A nevem...',
      'Where is the hotel?': 'Hol van a szálloda?',
      'Where is the airport?': 'Hol van a reptér?',
      'I speak a little': 'Egy kicsit beszélek',
      'Do you have wifi?': 'Van wifi?',
      'I have a reservation': 'Van foglalásom',
      "I'm allergic to...": 'Allergiás vagyok...',
      'How do I get to...?': 'Hogyan jutok el...?',
      'Can I pay by card?': 'Fizethetek kártyával?',
      'Where can I buy a ticket?': 'Hol vehetek jegyet?',
      'What time is it?': 'Hány óra van?',
      'See you later': 'Később találkozunk',
      'I need a taxi': 'Szükségem van egy taxira',
      'Is there a pharmacy nearby?': 'Van a közelben gyógyszertár?',
      'Call a doctor': 'Hívjon orvost',
      'I would like water': 'Szeretnék vizet',
      'Is this vegetarian?': 'Ez vegetáriánus?',
    },
  },
  et: {
    words: {
      I: 'mina',
      you: 'sina',
      friend: 'sõber',
      family: 'perekond',
      name: 'nimi',
      today: 'täna',
      tomorrow: 'homme',
      now: 'praegu',
      city: 'linn',
      street: 'tänav',
      shop: 'pood',
      pharmacy: 'apteek',
      police: 'politsei',
      ticket: 'pilet',
      coffee: 'kohv',
      bread: 'leib',
      beer: 'õlu',
      left: 'vasak',
      right: 'parem',
      near: 'lähedal',
      cheap: 'odav',
      expensive: 'kallis',
      open: 'avatud',
      closed: 'suletud',
      'to want': 'tahtma',
      'to buy': 'ostma',
      'to pay': 'maksma',
    },
    numbers: {
      '11': 'üksteist',
      '12': 'kaksteist',
      '13': 'kolmteist',
      '14': 'neliteist',
      '15': 'viisteist',
      '16': 'kuusteist',
      '17': 'seitseteist',
      '18': 'kaheksateist',
      '19': 'üheksateist',
      '60': 'kuuskümmend',
      '70': 'seitsekümmend',
      '80': 'kaheksakümmend',
      '90': 'üheksakümmend',
      '200': 'kakssada',
      '500': 'viissada',
    },
    sentences: {
      "What's your name?": 'Mis su nimi on?',
      'My name is...': 'Minu nimi on...',
      'Where is the hotel?': 'Kus on hotell?',
      'Where is the airport?': 'Kus on lennujaam?',
      'I speak a little': 'Ma räägin natuke',
      'Do you have wifi?': 'Kas teil on wifi?',
      'I have a reservation': 'Mul on broneering',
      "I'm allergic to...": 'Mul on allergia...',
      'How do I get to...?': 'Kuidas ma saan...?',
      'Can I pay by card?': 'Kas ma saan kaardiga maksta?',
      'Where can I buy a ticket?': 'Kust ma saan pileti osta?',
      'What time is it?': 'Mis kell on?',
      'See you later': 'Näeme hiljem',
      'I need a taxi': 'Mul on taksot vaja',
      'Is there a pharmacy nearby?': 'Kas lähedal on apteek?',
      'Call a doctor': 'Helistage arstile',
      'I would like water': 'Ma sooviksin vett',
      'Is this vegetarian?': 'Kas see on taimetoit?',
    },
  },
  hr: {
    words: {
      I: 'ja',
      you: 'ti',
      friend: 'prijatelj',
      family: 'obitelj',
      name: 'ime',
      today: 'danas',
      tomorrow: 'sutra',
      now: 'sada',
      city: 'grad',
      street: 'ulica',
      shop: 'trgovina',
      pharmacy: 'ljekarna',
      police: 'policija',
      ticket: 'karta',
      coffee: 'kava',
      bread: 'kruh',
      beer: 'pivo',
      left: 'lijevo',
      right: 'desno',
      near: 'blizu',
      cheap: 'jeftino',
      expensive: 'skupo',
      open: 'otvoreno',
      closed: 'zatvoreno',
      'to want': 'htjeti',
      'to buy': 'kupiti',
      'to pay': 'platiti',
    },
    numbers: {
      '11': 'jedanaest',
      '12': 'dvanaest',
      '13': 'trinaest',
      '14': 'četrnaest',
      '15': 'petnaest',
      '16': 'šesnaest',
      '17': 'sedamnaest',
      '18': 'osamnaest',
      '19': 'devetnaest',
      '60': 'šezdeset',
      '70': 'sedamdeset',
      '80': 'osamdeset',
      '90': 'devedeset',
      '200': 'dvjesto',
      '500': 'petsto',
    },
    sentences: {
      "What's your name?": 'Kako se zoveš?',
      'My name is...': 'Zovem se...',
      'Where is the hotel?': 'Gdje je hotel?',
      'Where is the airport?': 'Gdje je zračna luka?',
      'I speak a little': 'Govorim malo',
      'Do you have wifi?': 'Imate li wifi?',
      'I have a reservation': 'Imam rezervaciju',
      "I'm allergic to...": 'Alergičan sam na...',
      'How do I get to...?': 'Kako doći do...?',
      'Can I pay by card?': 'Mogu li platiti karticom?',
      'Where can I buy a ticket?': 'Gdje mogu kupiti kartu?',
      'What time is it?': 'Koliko je sati?',
      'See you later': 'Vidimo se',
      'I need a taxi': 'Trebam taksi',
      'Is there a pharmacy nearby?': 'Ima li ljekarna u blizini?',
      'Call a doctor': 'Nazovite liječnika',
      'I would like water': 'Želio bih vodu',
      'Is this vegetarian?': 'Je li ovo vegetarijansko?',
    },
  },
  hy: {
    words: {
      'I': 'ես',
      'you': 'դու',
      'friend': 'ընկեր',
      'family': 'ընտանիք',
      'name': 'անուն',
      'today': 'այսօր',
      'tomorrow': 'վաղը',
      'now': 'հիմա',
      'city': 'քաղաք',
      'street': 'փողոց',
      'shop': 'խանութ',
      'pharmacy': 'դեղատուն',
      'police': 'ոստիկանություն',
      'ticket': 'տոմս',
      'coffee': 'սուրճ',
      'bread': 'հաց',
      'beer': 'գարեջուր',
      'left': 'ձախ',
      'right': 'աջ',
      'near': 'մոտ',
      'cheap': 'էժան',
      'expensive': 'թանկ',
      'open': 'բաց',
      'closed': 'փակ',
      'to want': 'ուզել',
      'to buy': 'գնել',
      'to pay': 'վճարել',
    },
    numbers: {
      '11': 'տասնմեկ',
      '12': 'տասներկու',
      '13': 'տասներեք',
      '14': 'տասնչորս',
      '15': 'տասնհինգ',
      '16': 'տասնվեց',
      '17': 'տասնյոթ',
      '18': 'տասնութ',
      '19': 'տասնինը',
      '60': 'վաթսուն',
      '70': 'յոթանասուն',
      '80': 'ութսուն',
      '90': 'իննսուն',
      '200': 'երկու հարյուր',
      '500': 'հինգ հարյուր',
    },
    sentences: {
      'What\'s your name?': 'Ի՞նչ է քո անունը',
      'My name is...': 'Իմ անունն է...',
      'Where is the hotel?': 'Որտե՞ղ է հյուրանոցը',
      'Where is the airport?': 'Որտե՞ղ է օդանավակայանը',
      'I speak a little': 'Ես մի քիչ խոսում եմ',
      'Do you have wifi?': 'Ունե՞ք վայֆայ',
      'I have a reservation': 'Ես ամրագրում ունեմ',
      'I\'m allergic to...': 'Ես ալերգիա ունեմ...',
      'How do I get to...?': 'Ինչպե՞ս հասնել...',
      'Can I pay by card?': 'Կարո՞ղ եմ քարտով վճարել',
      'Where can I buy a ticket?': 'Որտե՞ղ կարող եմ տոմս գնել',
      'What time is it?': 'Որքա՞ն է ժամը',
      'See you later': 'Կտեսնվենք',
      'I need a taxi': 'Ինձ տաքսի է պետք',
      'Is there a pharmacy nearby?': 'Մոտակայքում դեղատուն կա՞',
      'Call a doctor': 'Կանչեք բժիշկ',
      'I would like water': 'Ես ջուր կուզեի',
      'Is this vegetarian?': 'Սա բուսական է՞',
    },
  },
  sk: {
    words: {
      I: 'ja',
      you: 'ty',
      friend: 'priateľ',
      family: 'rodina',
      name: 'meno',
      today: 'dnes',
      tomorrow: 'zajtra',
      now: 'teraz',
      city: 'mesto',
      street: 'ulica',
      shop: 'obchod',
      pharmacy: 'lekáreň',
      police: 'polícia',
      ticket: 'lístok',
      coffee: 'káva',
      bread: 'chlieb',
      beer: 'pivo',
      left: 'vľavo',
      right: 'vpravo',
      near: 'blízko',
      cheap: 'lacný',
      expensive: 'drahý',
      open: 'otvorené',
      closed: 'zatvorené',
      'to want': 'chcieť',
      'to buy': 'kúpiť',
      'to pay': 'platiť',
    },
    numbers: {
      '11': 'jedenásť',
      '12': 'dvanásť',
      '13': 'trinásť',
      '14': 'štrnásť',
      '15': 'pätnásť',
      '16': 'šestnásť',
      '17': 'sedemnásť',
      '18': 'osemnásť',
      '19': 'devätnásť',
      '60': 'šesťdesiat',
      '70': 'sedemdesiat',
      '80': 'osemdesiat',
      '90': 'deväťdesiat',
      '200': 'dvesto',
      '500': 'päťsto',
    },
    sentences: {
      "What's your name?": 'Ako sa voláš?',
      'My name is...': 'Volám sa...',
      'Where is the hotel?': 'Kde je hotel?',
      'Where is the airport?': 'Kde je letisko?',
      'I speak a little': 'Hovorím trochu',
      'Do you have wifi?': 'Máte wifi?',
      'I have a reservation': 'Mám rezerváciu',
      "I'm allergic to...": 'Som alergický na...',
      'How do I get to...?': 'Ako sa dostanem k...?',
      'Can I pay by card?': 'Môžem platiť kartou?',
      'Where can I buy a ticket?': 'Kde si môžem kúpiť lístok?',
      'What time is it?': 'Koľko je hodín?',
      'See you later': 'Uvidíme sa neskôr',
      'I need a taxi': 'Potrebujem taxi',
      'Is there a pharmacy nearby?': 'Je tu nablízku lekáreň?',
      'Call a doctor': 'Zavolajte lekára',
      'I would like water': 'Chcel by som vodu',
      'Is this vegetarian?': 'Je to vegetariánske?',
    },
  },
  sl: {
    words: {
      I: 'jaz',
      you: 'ti',
      friend: 'prijatelj',
      family: 'družina',
      name: 'ime',
      today: 'danes',
      tomorrow: 'jutri',
      now: 'zdaj',
      city: 'mesto',
      street: 'ulica',
      shop: 'trgovina',
      pharmacy: 'lekarna',
      police: 'policija',
      ticket: 'vozovnica',
      coffee: 'kava',
      bread: 'kruh',
      beer: 'pivo',
      left: 'levo',
      right: 'desno',
      near: 'blizu',
      cheap: 'poceni',
      expensive: 'drago',
      open: 'odprto',
      closed: 'zaprto',
      'to want': 'želeti',
      'to buy': 'kupiti',
      'to pay': 'plačati',
    },
    numbers: {
      '11': 'enajst',
      '12': 'dvanajst',
      '13': 'trinajst',
      '14': 'štirinajst',
      '15': 'petnajst',
      '16': 'šestnajst',
      '17': 'sedemnajst',
      '18': 'osemnajst',
      '19': 'devetnajst',
      '60': 'šestdeset',
      '70': 'sedemdeset',
      '80': 'osemdeset',
      '90': 'devetdeset',
      '200': 'dvesto',
      '500': 'petsto',
    },
    sentences: {
      "What's your name?": 'Kako ti je ime?',
      'My name is...': 'Ime mi je...',
      'Where is the hotel?': 'Kje je hotel?',
      'Where is the airport?': 'Kje je letališče?',
      'I speak a little': 'Govorim malo',
      'Do you have wifi?': 'Imate wifi?',
      'I have a reservation': 'Imam rezervacijo',
      "I'm allergic to...": 'Alergičen sem na...',
      'How do I get to...?': 'Kako pridem do...?',
      'Can I pay by card?': 'Lahko plačam s kartico?',
      'Where can I buy a ticket?': 'Kje lahko kupim vozovnico?',
      'What time is it?': 'Koliko je ura?',
      'See you later': 'Se vidimo',
      'I need a taxi': 'Potrebujem taksi',
      'Is there a pharmacy nearby?': 'Je v bližini lekarna?',
      'Call a doctor': 'Pokličite zdravnika',
      'I would like water': 'Rad bi vodo',
      'Is this vegetarian?': 'Je to vegetarijansko?',
    },
  },
  uk: {
    words: {
      I: 'я (ya)',
      you: 'ти (ty)',
      friend: 'друг (druh)',
      family: 'сім\'я (simia)',
      name: 'ім\'я (imia)',
      today: 'сьогодні (sohodni)',
      tomorrow: 'завтра (zavtra)',
      now: 'зараз (zaraz)',
      city: 'місто (misto)',
      street: 'вулиця (vulytsia)',
      shop: 'магазин (mahazyn)',
      pharmacy: 'аптека (apteka)',
      police: 'поліція (politsiia)',
      ticket: 'квиток (kvytok)',
      coffee: 'кава (kava)',
      bread: 'хліб (khlib)',
      beer: 'пиво (pyvo)',
      left: 'ліворуч (livoruch)',
      right: 'праворуч (pravoruch)',
      near: 'поблизу (poblyzu)',
      cheap: 'дешевий (deshevyi)',
      expensive: 'дорогий (dorohyi)',
      open: 'відкрито (vidkryto)',
      closed: 'зачинено (zachyneno)',
      'to want': 'хотіти (khotity)',
      'to buy': 'купити (kupyty)',
      'to pay': 'платити (platyty)',
    },
    numbers: {
      '11': 'одинадцять (odynadtsiat)',
      '12': 'дванадцять (dvanadtsiat)',
      '13': 'тринадцять (trynadtsiat)',
      '14': 'чотирнадцять (chotyrnadtsiat)',
      '15': 'п\'ятнадцять (piatnadtsiat)',
      '16': 'шістнадцять (shistnadtsiat)',
      '17': 'сімнадцять (simnadtsiat)',
      '18': 'вісімнадцять (visimnadtsiat)',
      '19': 'дев\'ятнадцять (deviatnadtsiat)',
      '60': 'шістдесят (shistdesiat)',
      '70': 'сімдесят (simdesiat)',
      '80': 'вісімдесят (visimdesiat)',
      '90': 'дев\'яносто (devianosto)',
      '200': 'двісті (dvisti)',
      '500': 'п\'ятсот (piatsot)',
    },
    sentences: {
      "What's your name?": 'Як вас звати? (Yak vas zvaty?)',
      'My name is...': 'Мене звати... (Mene zvaty...)',
      'Where is the hotel?': 'Де готель? (De hotel?)',
      'Where is the airport?': 'Де аеропорт? (De aeroport?)',
      'I speak a little': 'Я трохи розмовляю (Ya trokhy rozmovliaiu)',
      'Do you have wifi?': 'У вас є wifi? (U vas ye wifi?)',
      'I have a reservation': 'У мене є бронювання (U mene ye broniuvannia)',
      "I'm allergic to...": 'У мене алергія на... (U mene alerhiia na...)',
      'How do I get to...?': 'Як дістатися до...? (Yak distatysia do...?)',
      'Can I pay by card?': 'Чи можна оплатити карткою? (Chy mozhna oplatyty kartkoiu?)',
      'Where can I buy a ticket?':
        'Де можна купити квиток? (De mozhna kupyty kvytok?)',
      'What time is it?': 'Котра година? (Kotra hodyna?)',
      'See you later': 'Побачимося (Pobachymosia)',
      'I need a taxi': 'Мені потрібне таксі (Meni potribne taksi)',
      'Is there a pharmacy nearby?':
        'Чи є аптека поблизу? (Chy ye apteka poblyzu?)',
      'Call a doctor': 'Викличте лікаря (Vyklychte likaria)',
      'I would like water': 'Я б хотів води (Ya b khotiv vody)',
      'Is this vegetarian?': 'Це вегетаріанське? (Tse vehetarianske?)',
    },
  },
};



